// Auto-generated by scripts/generate-component-story-previews.mjs. Do not edit manually.
// Maps PascalCase component names to Storybook-backed preview fixtures.
// Stories from apps/docs/src/ are always included; stories from src/stories/
// are included only after verifying all @/ imports resolve in the docs app.

"use client";

import dynamic from "next/dynamic";
import { createStoryPreview } from "@/components/story-preview-renderer";

export const componentStoryPreviews: Record<string, React.ComponentType> = {
  Accordion: dynamic(
    () =>
      import("../../src/components/Accordion.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Affix: dynamic(
    () =>
      import("../../src/components/Affix.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  AlertDialog: dynamic(
    () =>
      import("../../src/components/AlertDialog.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Alert: dynamic(
    () =>
      import("../../src/components/Alert.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Anchor: dynamic(
    () =>
      import("../../src/business/Anchor.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  AspectRatio: dynamic(
    () =>
      import("../../src/components/AspectRatio.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  AudioPlayer: dynamic(
    () =>
      import("../../src/business/AudioPlayer.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Autocomplete: dynamic(
    () =>
      import("../../src/components/Autocomplete.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Avatar: dynamic(
    () =>
      import("../../src/components/Avatar.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  BackTop: dynamic(
    () =>
      import("../../src/components/BackTop.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Badge: dynamic(
    () =>
      import("../../src/components/Badge.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  BarcodeDisplay: dynamic(
    () =>
      import("../../src/business/BarcodeDisplay.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Breadcrumb: dynamic(
    () =>
      import("../../src/components/Breadcrumb.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  BrowseInput: dynamic(
    () =>
      import("../../src/components/BrowseInput.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Button: dynamic(
    () =>
      import("../../src/components/Button.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Calendar: dynamic(
    () =>
      import("../../src/components/Calendar.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Card: dynamic(
    () =>
      import("../../src/components/Card.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Carousel: dynamic(
    () =>
      import("../../src/components/Carousel.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Cascader: dynamic(
    () =>
      import("../../src/components/Cascader.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Checkbox: dynamic(
    () =>
      import("../../src/components/Checkbox.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Collapsible: dynamic(
    () =>
      import("../../src/components/Collapsible.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ColorPicker: dynamic(
    () =>
      import("../../src/components/ColorPicker.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Command: dynamic(
    () =>
      import("../../src/components/Command.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ConfigProvider: dynamic(
    () =>
      import("../../src/components/ConfigProvider.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Countdown: dynamic(
    () =>
      import("../../src/components/Countdown.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  DatePicker: dynamic(
    () =>
      import("../../src/components/DatePicker.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  DepartmentBrowse: dynamic(
    () =>
      import("../../src/components/DepartmentBrowse.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Descriptions: dynamic(
    () =>
      import("../../src/components/Descriptions.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Dialog: dynamic(
    () =>
      import("../../src/components/Dialog.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Divider: dynamic(
    () =>
      import("../../src/components/Divider.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Dot: dynamic(
    () =>
      import("../../src/components/Dot.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Drawer: dynamic(
    () =>
      import("../../src/components/Drawer.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  DropdownMenu: dynamic(
    () =>
      import("../../src/components/DropdownMenu.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  FileUpload: dynamic(
    () =>
      import("../../src/components/FileUpload.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Flex: dynamic(
    () =>
      import("../../src/components/Flex.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  FormGrid: dynamic(
    () =>
      import("../../src/components/FormGrid.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  FormList: dynamic(
    () =>
      import("../../src/components/FormList.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  FormSection: dynamic(
    () =>
      import("../../src/components/FormSection.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Form: dynamic(
    () =>
      import("../../src/business/Form.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  FullscreenToggle: dynamic(
    () =>
      import("../../src/components/FullscreenToggle.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  GridLayout: dynamic(
    () =>
      import("../../src/components/GridLayout.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Grid: dynamic(
    () =>
      import("../../src/components/Grid.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  HoverCard: dynamic(
    () =>
      import("../../src/components/HoverCard.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  IconPicker: dynamic(
    () =>
      import("../../src/components/IconPicker.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ImageViewer: dynamic(
    () =>
      import("../../src/components/ImageViewer.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Image: dynamic(
    () =>
      import("../../src/components/Image.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  InputGroup: dynamic(
    () =>
      import("../../src/components/InputGroup.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  InputNumber: dynamic(
    () =>
      import("../../src/components/InputNumber.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  InputSearch: dynamic(
    () =>
      import("../../src/components/InputSearch.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Input: dynamic(
    () =>
      import("../../src/components/Input.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Kbd: dynamic(
    () =>
      import("../../src/components/Kbd.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  KeyboardShortcut: dynamic(
    () =>
      import("../../src/components/KeyboardShortcut.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Label: dynamic(
    () =>
      import("../../src/components/Label.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  List: dynamic(
    () =>
      import("../../src/components/List.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Mentions: dynamic(
    () =>
      import("../../src/components/Mentions.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  NavigationMenu: dynamic(
    () =>
      import("../../src/components/NavigationMenu.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Notification: dynamic(
    () =>
      import("../../src/components/Notification.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  NumberTicker: dynamic(
    () =>
      import("../../src/components/NumberTicker.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  OtpField: dynamic(
    () =>
      import("../../src/components/OtpField.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  PageContainer: dynamic(
    () =>
      import("../../src/components/PageContainer.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Pagination: dynamic(
    () =>
      import("../../src/components/Pagination.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Popover: dynamic(
    () =>
      import("../../src/components/Popover.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Progress: dynamic(
    () =>
      import("../../src/components/Progress.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  QrcodeDisplay: dynamic(
    () =>
      import("../../src/components/QrcodeDisplay.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Qrcode: dynamic(
    () =>
      import("../../src/components/Qrcode.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  RadioGroup: dynamic(
    () =>
      import("../../src/components/RadioGroup.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Resizable: dynamic(
    () =>
      import("../../src/components/Resizable.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ScrollArea: dynamic(
    () =>
      import("../../src/components/ScrollArea.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Select: dynamic(
    () =>
      import("../../src/components/Select.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Separator: dynamic(
    () =>
      import("../../src/components/Separator.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  SequenceInput: dynamic(
    () =>
      import("../../src/components/SequenceInput.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  SequencePreview: dynamic(
    () =>
      import("../../src/components/SequencePreview.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Sheet: dynamic(
    () =>
      import("../../src/components/Sheet.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Sidebar: dynamic(
    () =>
      import("../../src/components/Sidebar.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  SignaturePad: dynamic(
    () =>
      import("../../src/business/SignaturePad.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Skeleton: dynamic(
    () =>
      import("../../src/components/Skeleton.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Slider: dynamic(
    () =>
      import("../../src/components/Slider.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Sonner: dynamic(
    () =>
      import("../../src/components/Sonner.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Space: dynamic(
    () =>
      import("../../src/components/Space.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Spin: dynamic(
    () =>
      import("../../src/components/Spin.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Spinner: dynamic(
    () =>
      import("../../src/components/Spinner.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  SplitButton: dynamic(
    () =>
      import("../../src/components/SplitButton.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  SplitPane: dynamic(
    () =>
      import("../../src/components/SplitPane.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Statistic: dynamic(
    () =>
      import("../../src/components/Statistic.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Stepper: dynamic(
    () =>
      import("../../src/components/Stepper.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Switch: dynamic(
    () =>
      import("../../src/components/Switch.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Table: dynamic(
    () =>
      import("../../src/components/Table.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Tabs: dynamic(
    () =>
      import("../../src/components/Tabs.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Tag: dynamic(
    () =>
      import("../../src/components/Tag.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  TagsInput: dynamic(
    () =>
      import("../../src/components/TagsInput.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Textarea: dynamic(
    () =>
      import("../../src/components/Textarea.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Timeline: dynamic(
    () =>
      import("../../src/components/Timeline.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ToggleGroup: dynamic(
    () =>
      import("../../src/components/ToggleGroup.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Toggle: dynamic(
    () =>
      import("../../src/components/Toggle.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Tooltip: dynamic(
    () =>
      import("../../src/components/Tooltip.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  TreeSelect: dynamic(
    () =>
      import("../../src/components/TreeSelect.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  TreeView: dynamic(
    () =>
      import("../../src/components/TreeView.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Typography: dynamic(
    () =>
      import("../../src/components/Typography.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  UserBrowse: dynamic(
    () =>
      import("../../src/components/UserBrowse.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  VideoPlayer: dynamic(
    () =>
      import("../../src/business/VideoPlayer.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  VirtualList: dynamic(
    () =>
      import("../../src/components/VirtualList.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  VirtualTable: dynamic(
    () =>
      import("../../src/components/VirtualTable.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  AdminBreadcrumb: dynamic(
    () =>
      import("../../src/layout/AdminBreadcrumb.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  AdminHeader: dynamic(
    () =>
      import("../../src/layout/AdminHeader.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  AdminSider: dynamic(
    () =>
      import("../../src/layout/AdminSider.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  AdminTabs: dynamic(
    () =>
      import("../../src/layout/AdminTabs.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  AppShell: dynamic(
    () =>
      import("../../src/layout/AppShell.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  AuthLayout: dynamic(
    () =>
      import("../../src/layout/AuthLayout.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  BlankLayout: dynamic(
    () =>
      import("../../src/layout/BlankLayout.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  DashboardLayout: dynamic(
    () =>
      import("../../src/layout/DashboardLayout.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  DetailLayout: dynamic(
    () =>
      import("../../src/layout/DetailLayout.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  DialogFormBody: dynamic(
    () =>
      import("../../src/layout/DialogFormBody.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ErrorLayout: dynamic(
    () =>
      import("../../src/layout/ErrorLayout.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MasterDetailLayout: dynamic(
    () =>
      import("../../src/layout/MasterDetailLayout.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MasterDetailTabs: dynamic(
    () =>
      import("../../src/layout/MasterDetailTabs.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  PrintLayout: dynamic(
    () =>
      import("../../src/layout/PrintLayout.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  PublicLayout: dynamic(
    () =>
      import("../../src/layout/PublicLayout.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  RegionLayout: dynamic(
    () =>
      import("../../src/layout/RegionLayout.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  TopBar: dynamic(
    () =>
      import("../../src/layout/TopBar.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ActivityFeed: dynamic(
    () =>
      import("../../src/business/ActivityFeed.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  AddressPicker: dynamic(
    () =>
      import("../../src/business/AddressPicker.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  AdvancedDataTable: dynamic(
    () =>
      import("../../src/business/AdvancedDataTable.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  AdvancedSearch: dynamic(
    () =>
      import("../../src/business/AdvancedSearch.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ApprovalFlow: dynamic(
    () =>
      import("../../src/business/ApprovalFlow.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ApprovalTimeline: dynamic(
    () =>
      import("../../src/business/ApprovalTimeline.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  AreaChart: dynamic(
    () =>
      import("../../src/business/AreaChart.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  AsyncTaskCenter: dynamic(
    () =>
      import("../../src/business/AsyncTaskCenter.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  AudienceSegmentBuilder: dynamic(
    () =>
      import("../../src/business/AudienceSegmentBuilder.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  AuditLog: dynamic(
    () =>
      import("../../src/business/AuditLog.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  AuditSidebar: dynamic(
    () =>
      import("../../src/business/AuditSidebar.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  AuthGuard: dynamic(
    () =>
      import("../../src/business/AuthGuard.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  BarChart: dynamic(
    () =>
      import("../../src/business/BarChart.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  BatchSelector: dynamic(
    () =>
      import("../../src/business/BatchSelector.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  BillFooter: dynamic(
    () =>
      import("../../src/business/BillFooter.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  BillHeader: dynamic(
    () =>
      import("../../src/business/BillHeader.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  BillPage: dynamic(
    () =>
      import("../../src/business/BillPage.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  BudgetPacingCard: dynamic(
    () =>
      import("../../src/business/BudgetPacingCard.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  BulkActionsToolbar: dynamic(
    () =>
      import("../../src/business/BulkActionsToolbar.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  BulkImportWizard: dynamic(
    () =>
      import("../../src/business/BulkImportWizard.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  CampaignCalendar: dynamic(
    () =>
      import("../../src/business/CampaignCalendar.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  CampaignStatusTag: dynamic(
    () =>
      import("../../src/business/CampaignStatusTag.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ChannelPicker: dynamic(
    () =>
      import("../../src/business/ChannelPicker.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Chart: dynamic(
    () =>
      import("../../src/business/Chart.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Chip: dynamic(
    () =>
      import("../../src/business/Chip.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  CodeBlock: dynamic(
    () =>
      import("../../src/business/CodeBlock.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  CodeEditor: dynamic(
    () =>
      import("../../src/business/CodeEditor.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ColorTag: dynamic(
    () =>
      import("../../src/business/ColorTag.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Combobox: dynamic(
    () =>
      import("../../src/business/Combobox.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  CommandPalette: dynamic(
    () =>
      import("../../src/business/CommandPalette.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ConfirmDialog: dynamic(
    () =>
      import("../../src/business/ConfirmDialog.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ContractTemplate: dynamic(
    () =>
      import("../../src/business/ContractTemplate.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  CookieBanner: dynamic(
    () =>
      import("../../src/business/CookieBanner.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  CreativePreview: dynamic(
    () =>
      import("../../src/business/CreativePreview.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  CrudPage: dynamic(
    () =>
      import("../../src/business/CrudPage.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  CrudToolbar: dynamic(
    () =>
      import("../../src/business/CrudToolbar.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  DashboardDesigner: dynamic(
    () =>
      import("../../src/business/DashboardDesigner.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  DataTable: dynamic(
    () =>
      import("../../src/business/DataTable.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  DateRangePicker: dynamic(
    () =>
      import("../../src/business/DateRangePicker.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  DictSelect: dynamic(
    () =>
      import("../../src/business/DictSelect.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  DiffViewerTable: dynamic(
    () =>
      import("../../src/business/DiffViewerTable.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  DiffViewer: dynamic(
    () =>
      import("../../src/business/DiffViewer.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  EditToolbar: dynamic(
    () =>
      import("../../src/business/EditToolbar.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  EditableTreeTable: dynamic(
    () =>
      import("../../src/business/EditableTreeTable.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  EmptyState: dynamic(
    () =>
      import("../../src/business/EmptyState.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  EquipmentCard: dynamic(
    () =>
      import("../../src/business/EquipmentCard.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ErrorBoundary: dynamic(
    () =>
      import("../../src/business/ErrorBoundary.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ErrorPage: dynamic(
    () =>
      import("../../src/business/ErrorPage.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ExpenseLineEditor: dynamic(
    () =>
      import("../../src/business/ExpenseLineEditor.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ExperimentSummary: dynamic(
    () =>
      import("../../src/business/ExperimentSummary.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ExportButton: dynamic(
    () =>
      import("../../src/business/ExportButton.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Fab: dynamic(
    () =>
      import("../../src/business/Fab.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  FieldMask: dynamic(
    () =>
      import("../../src/business/FieldMask.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  FileUploadManager: dynamic(
    () =>
      import("../../src/business/FileUploadManager.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  FilterBar: dynamic(
    () =>
      import("../../src/business/FilterBar.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  FilterBuilder: dynamic(
    () =>
      import("../../src/business/FilterBuilder.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Forbidden: dynamic(
    () =>
      import("../../src/business/Forbidden.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  FormField: dynamic(
    () =>
      import("../../src/business/FormField.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  FormWizard: dynamic(
    () =>
      import("../../src/business/FormWizard.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  FormulaEditor: dynamic(
    () =>
      import("../../src/business/FormulaEditor.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  FunnelChart: dynamic(
    () =>
      import("../../src/business/FunnelChart.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  GanttChart: dynamic(
    () =>
      import("../../src/business/GanttChart.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Gauge: dynamic(
    () =>
      import("../../src/business/Gauge.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  GlobalLoading: dynamic(
    () =>
      import("../../src/business/GlobalLoading.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  HeatmapCalendar: dynamic(
    () =>
      import("../../src/business/HeatmapCalendar.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  HeatmapChart: dynamic(
    () =>
      import("../../src/business/HeatmapChart.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ImageGallery: dynamic(
    () =>
      import("../../src/business/ImageGallery.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ImportDialog: dynamic(
    () =>
      import("../../src/business/ImportDialog.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  InlineEdit: dynamic(
    () =>
      import("../../src/business/InlineEdit.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  InventoryAlertList: dynamic(
    () =>
      import("../../src/business/InventoryAlertList.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  JsonViewer: dynamic(
    () =>
      import("../../src/business/JsonViewer.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  KanbanBoard: dynamic(
    () =>
      import("../../src/business/KanbanBoard.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  KpiCard: dynamic(
    () =>
      import("../../src/business/KpiCard.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  LanguageSwitcher: dynamic(
    () =>
      import("../../src/business/LanguageSwitcher.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  LineChart: dynamic(
    () =>
      import("../../src/business/LineChart.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  LineEditor: dynamic(
    () =>
      import("../../src/business/LineEditor.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  LoadingPage: dynamic(
    () =>
      import("../../src/business/LoadingPage.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MaintenanceLog: dynamic(
    () =>
      import("../../src/business/MaintenanceLog.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MapView: dynamic(
    () =>
      import("../../src/business/MapView.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MetricTrend: dynamic(
    () =>
      import("../../src/business/MetricTrend.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MultiSelect: dynamic(
    () =>
      import("../../src/business/MultiSelect.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  NotificationCenter: dynamic(
    () =>
      import("../../src/business/NotificationCenter.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  OrderLineEditor: dynamic(
    () =>
      import("../../src/business/OrderLineEditor.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  OrgChart: dynamic(
    () =>
      import("../../src/business/OrgChart.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  PageHeader: dynamic(
    () =>
      import("../../src/business/PageHeader.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  PdfViewer: dynamic(
    () =>
      import("../../src/business/PdfViewer.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  PermissionMatrix: dynamic(
    () =>
      import("../../src/business/PermissionMatrix.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  PermissionWrapper: dynamic(
    () =>
      import("../../src/business/PermissionWrapper.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  PieChart: dynamic(
    () =>
      import("../../src/business/PieChart.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  PivotTable: dynamic(
    () =>
      import("../../src/business/PivotTable.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  PrintButton: dynamic(
    () =>
      import("../../src/business/PrintButton.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  PromptDialog: dynamic(
    () =>
      import("../../src/business/PromptDialog.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  QualityInspectionForm: dynamic(
    () =>
      import("../../src/business/QualityInspectionForm.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  RadarChart: dynamic(
    () =>
      import("../../src/business/RadarChart.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  RadialChart: dynamic(
    () =>
      import("../../src/business/RadialChart.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Rating: dynamic(
    () =>
      import("../../src/business/Rating.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  RemoteSelect: dynamic(
    () =>
      import("../../src/business/RemoteSelect.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ReportBuilder: dynamic(
    () =>
      import("../../src/business/ReportBuilder.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ResponsivePreview: dynamic(
    () =>
      import("../../src/business/ResponsivePreview.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  RichTextEditor: dynamic(
    () =>
      import("../../src/business/RichTextEditor.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  RoleAssignment: dynamic(
    () =>
      import("../../src/business/RoleAssignment.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  SankeyChart: dynamic(
    () =>
      import("../../src/business/SankeyChart.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  SavedFilters: dynamic(
    () =>
      import("../../src/business/SavedFilters.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ScatterChart: dynamic(
    () =>
      import("../../src/business/ScatterChart.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  SearchTable: dynamic(
    () =>
      import("../../src/business/SearchTable.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  SegmentedControl: dynamic(
    () =>
      import("../../src/business/SegmentedControl.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ShiftCalendar: dynamic(
    () =>
      import("../../src/business/ShiftCalendar.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  StatCardRow: dynamic(
    () =>
      import("../../src/business/StatCardRow.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  StatCard: dynamic(
    () =>
      import("../../src/business/StatCard.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  StatusBadge: dynamic(
    () =>
      import("../../src/business/StatusBadge.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  StatusTag: dynamic(
    () =>
      import("../../src/business/StatusTag.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  ThemeToggle: dynamic(
    () =>
      import("../../src/business/ThemeToggle.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  TimePicker: dynamic(
    () =>
      import("../../src/business/TimePicker.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Tour: dynamic(
    () =>
      import("../../src/business/Tour.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Transfer: dynamic(
    () =>
      import("../../src/business/Transfer.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  TreeTable: dynamic(
    () =>
      import("../../src/business/TreeTable.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  TreemapChart: dynamic(
    () =>
      import("../../src/business/TreemapChart.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  UnitConverter: dynamic(
    () =>
      import("../../src/business/UnitConverter.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  UserMenu: dynamic(
    () =>
      import("../../src/business/UserMenu.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  UtmBuilder: dynamic(
    () =>
      import("../../src/business/UtmBuilder.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  VersionHistory: dynamic(
    () =>
      import("../../src/business/VersionHistory.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  WaterfallChart: dynamic(
    () =>
      import("../../src/business/WaterfallChart.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  Watermark: dynamic(
    () =>
      import("../../src/business/Watermark.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileAuthLayout: dynamic(
    () =>
      import("../../src/business/MobileAuthLayout.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileBottomNav: dynamic(
    () =>
      import("../../src/business/MobileBottomNav.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileButton: dynamic(
    () =>
      import("../../src/business/MobileButton.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileCard: dynamic(
    () =>
      import("../../src/business/MobileCard.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileDashboardLayout: dynamic(
    () =>
      import("../../src/business/MobileDashboardLayout.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileDataTable: dynamic(
    () =>
      import("../../src/business/MobileDataTable.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileDialog: dynamic(
    () =>
      import("../../src/business/MobileDialog.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileEmptyState: dynamic(
    () =>
      import("../../src/business/MobileEmptyState.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileFilterBuilder: dynamic(
    () =>
      import("../../src/business/MobileFilterBuilder.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileFormField: dynamic(
    () =>
      import("../../src/business/MobileFormField.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileFormWizard: dynamic(
    () =>
      import("../../src/business/MobileFormWizard.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileForm: dynamic(
    () =>
      import("../../src/business/MobileForm.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileInput: dynamic(
    () =>
      import("../../src/business/MobileInput.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileKanban: dynamic(
    () =>
      import("../../src/business/MobileKanban.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileKpiCard: dynamic(
    () =>
      import("../../src/business/MobileKpiCard.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileNavigation: dynamic(
    () =>
      import("../../src/business/MobileNavigation.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobilePageHeader: dynamic(
    () =>
      import("../../src/business/MobilePageHeader.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobilePullToRefresh: dynamic(
    () =>
      import("../../src/business/MobilePullToRefresh.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileSelect: dynamic(
    () =>
      import("../../src/business/MobileSelect.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileSheet: dynamic(
    () =>
      import("../../src/business/MobileSheet.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileSkeleton: dynamic(
    () =>
      import("../../src/business/MobileSkeleton.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileSwipeActions: dynamic(
    () =>
      import("../../src/business/MobileSwipeActions.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileTabs: dynamic(
    () =>
      import("../../src/business/MobileTabs.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
  MobileTextarea: dynamic(
    () =>
      import("../../src/business/MobileTextarea.stories").then((m) => ({
        default: createStoryPreview(m),
      })),
    { ssr: false },
  ),
};
