// Auto-generated by scripts/generate-component-map.mjs. Do not edit manually.
// Maps PascalCase component names to their React component implementations.
// Used by the component detail page to render live previews.

import { Accordion } from "@/components/ui/accordion";
import { Affix } from "@/components/ui/affix";
import { AlertDialog } from "@/components/ui/alert-dialog";
import { Alert } from "@/components/ui/alert";
import { Anchor } from "@/components/ui/anchor";
import { AspectRatio } from "@/components/ui/aspect-ratio";
import { AudioPlayer } from "@/components/ui/audio-player";
import { Autocomplete } from "@/components/ui/autocomplete";
import { Avatar } from "@/components/ui/avatar";
import { BackTop } from "@/components/ui/back-top";
import { Badge } from "@/components/ui/badge";
import { BarcodeDisplay } from "@/components/ui/barcode-display";
import { Breadcrumb } from "@/components/ui/breadcrumb";
import { BrowseInput } from "@/components/ui/browse-input";
import { Button } from "@/components/ui/button";
import { Calendar } from "@/components/ui/calendar";
import { Card } from "@/components/ui/card";
import { Carousel } from "@/components/ui/carousel";
import { Cascader } from "@/components/ui/cascader";
import { ChatInput } from "@/components/ui/chat-input";
import { ChatMessage } from "@/components/ui/chat-message";
import { Checkbox } from "@/components/ui/checkbox";
import { Collapsible } from "@/components/ui/collapsible";
import { ColorPicker } from "@/components/ui/color-picker";
import { Combobox } from "@/components/ui/combobox";
import { Command } from "@/components/ui/command";
import { ConfigProvider } from "@/components/ui/config-provider";
import { ContextMenu } from "@/components/ui/context-menu";
import { Countdown } from "@/components/ui/countdown";
import { DatePicker } from "@/components/ui/date-picker";
import { DepartmentBrowse } from "@/components/ui/department-browse";
import { Descriptions } from "@/components/ui/descriptions";
import { Dialog } from "@/components/ui/dialog";
import { Direction } from "@/components/ui/direction";
import { Divider } from "@/components/ui/divider";
import { Dot } from "@/components/ui/dot";
import { Drawer } from "@/components/ui/drawer";
import { DropdownMenu } from "@/components/ui/dropdown-menu";
import { EmptyState } from "@/components/ui/empty-state";
import { Fab } from "@/components/ui/fab";
import { FileUpload } from "@/components/ui/file-upload";
import { Flex } from "@/components/ui/flex";
import { FormGrid } from "@/components/ui/form-grid";
import { FormList } from "@/components/ui/form-list";
import { FormSection } from "@/components/ui/form-section";
import { Form } from "@/components/ui/form";
import { FullscreenToggle } from "@/components/ui/fullscreen-toggle";
import { GridLayout } from "@/components/ui/grid-layout";
import { Grid } from "@/components/ui/grid";
import { HoverCard } from "@/components/ui/hover-card";
import { IconPicker } from "@/components/ui/icon-picker";
import { Icon } from "@/components/ui/icon";
import { ImageViewer } from "@/components/ui/image-viewer";
import { Image } from "@/components/ui/image";
import { InfiniteScroll } from "@/components/ui/infinite-scroll";
import { InputGroup } from "@/components/ui/input-group";
import { InputNumber } from "@/components/ui/input-number";
import { InputSearch } from "@/components/ui/input-search";
import { Input } from "@/components/ui/input";
import { Kbd } from "@/components/ui/kbd";
import { KeyboardShortcutDialog } from "@/components/ui/keyboard-shortcut-dialog";
import { KeyboardShortcut } from "@/components/ui/keyboard-shortcut";
import { KPIPanel as KpiPanel } from "@/components/ui/kpi-panel";
import { Label } from "@/components/ui/label";
import { List } from "@/components/ui/list";
import { Masonry } from "@/components/ui/masonry";
import { Mentions } from "@/components/ui/mentions";
import { Menu } from "@/components/ui/menu";
import { Menubar } from "@/components/ui/menubar";
import { MessageProvider } from "@/components/ui/message-provider";
import { Message } from "@/components/ui/message";
import { MobilePullRefresh } from "@/components/ui/mobile-pull-refresh";
import { MobileSwipeAction } from "@/components/ui/mobile-swipe-action";
import { ModalProvider } from "@/components/ui/modal-provider";
import { NativeSelect } from "@/components/ui/native-select";
import { NavigationMenu } from "@/components/ui/navigation-menu";
import { Notification } from "@/components/ui/notification";
import { NumberTicker } from "@/components/ui/number-ticker";
import { OTPField as OtpField } from "@/components/ui/otp-field";
import { PageContainer } from "@/components/ui/page-container";
import { Pagination } from "@/components/ui/pagination";
import { Popconfirm } from "@/components/ui/popconfirm";
import { Popover } from "@/components/ui/popover";
import { Progress } from "@/components/ui/progress";
import { QRCodeDisplay as QrcodeDisplay } from "@/components/ui/qrcode-display";
import { QRCode as Qrcode } from "@/components/ui/qrcode";
import { RadioGroup } from "@/components/ui/radio-group";
import { Rating } from "@/components/ui/rating";
import { ResizablePanelGroup as Resizable } from "@/components/ui/resizable";
import { Result } from "@/components/ui/result";
import { SchemaForm } from "@/components/ui/schema-form";
import { ScrollArea } from "@/components/ui/scroll-area";
import { SegmentedControl } from "@/components/ui/segmented-control";
import { Select } from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { SequenceInput } from "@/components/ui/sequence-input";
import { SequencePreview } from "@/components/ui/sequence-preview";
import { Sheet } from "@/components/ui/sheet";
import { Sidebar } from "@/components/ui/sidebar";
import { SignaturePad } from "@/components/ui/signature-pad";
import { Skeleton } from "@/components/ui/skeleton";
import { Slider } from "@/components/ui/slider";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { Space } from "@/components/ui/space";
import { Spin } from "@/components/ui/spin";
import { Spinner } from "@/components/ui/spinner";
import { SplitButton } from "@/components/ui/split-button";
import { SplitPane } from "@/components/ui/split-pane";
import { Statistic } from "@/components/ui/statistic";
import { Stepper } from "@/components/ui/stepper";
import { Switch } from "@/components/ui/switch";
import { Table } from "@/components/ui/table";
import { Tabs } from "@/components/ui/tabs";
import { Tag } from "@/components/ui/tag";
import { TagsInput } from "@/components/ui/tags-input";
import { Textarea } from "@/components/ui/textarea";
import { TimePicker } from "@/components/ui/time-picker";
import { Timeline } from "@/components/ui/timeline";
import { ToggleGroup } from "@/components/ui/toggle-group";
import { Toggle } from "@/components/ui/toggle";
import { Tooltip } from "@/components/ui/tooltip";
import { Tour } from "@/components/ui/tour";
import { Transfer } from "@/components/ui/transfer";
import { TreeSelect } from "@/components/ui/tree-select";
import { TreeView } from "@/components/ui/tree-view";
import { Typography } from "@/components/ui/typography";
import { UserBrowse } from "@/components/ui/user-browse";
import { VideoPlayer } from "@/components/ui/video-player";
import { VirtualList } from "@/components/ui/virtual-list";
import { VirtualTable } from "@/components/ui/virtual-table";
import { Watermark } from "@/components/ui/watermark";
import { WithPermission } from "@/components/ui/with-permission";
import { AdminBreadcrumb } from "@/components/layout/admin-breadcrumb";
import { AdminHeader } from "@/components/layout/admin-header";
import { AdminShell } from "@/components/layout/admin-shell";
import { AdminSider } from "@/components/layout/admin-sider";
import { AdminTabs } from "@/components/layout/admin-tabs";
import { AppShell } from "@/components/layout/app-shell";
import { ArticleLayout } from "@/components/layout/article-layout";
import { AuthLayout } from "@/components/layout/auth-layout";
import { BlankLayout } from "@/components/layout/blank-layout";
import { ChatLayout } from "@/components/layout/chat-layout";
import { DashboardLayout } from "@/components/layout/dashboard-layout";
import { DetailLayout } from "@/components/layout/detail-layout";
import { DialogFormBody } from "@/components/layout/dialog-form-body";
import { EmbedLayout } from "@/components/layout/embed-layout";
import { ErrorLayout } from "@/components/layout/error-layout";
import { MasterDetailLayout } from "@/components/layout/master-detail-layout";
import { MasterDetailTabs } from "@/components/layout/master-detail-tabs";
import { NavigationTabsBar } from "@/components/layout/navigation-tabs-bar";
import { PrintLayout } from "@/components/layout/print-layout";
import { PrintTemplateLayout } from "@/components/layout/print-template-layout";
import { PublicLayout } from "@/components/layout/public-layout";
import { RegionLayout } from "@/components/layout/region-layout";
import { SplitScreen } from "@/components/layout/split-screen";
import { TopBar } from "@/components/layout/top-bar";
import { WizardLayout } from "@/components/layout/wizard-layout";
import { AccountBalance } from "@/components/business/account-balance";
import { ActivityFeed } from "@/components/business/activity-feed";
import { AddressPicker } from "@/components/business/address-picker";
import { AdvancedDataTable } from "@/components/business/advanced-data-table";
import { AdvancedSearch } from "@/components/business/advanced-search";
import { AnnouncementBanner } from "@/components/business/announcement-banner";
import { AnnouncementCard } from "@/components/business/announcement-card";
import { ApplicationForm } from "@/components/business/application-form";
import { ApprovalActionBar } from "@/components/business/approval-action-bar";
import { ApprovalFlow } from "@/components/business/approval-flow";
import { ApprovalTimeline } from "@/components/business/approval-timeline";
import { ArApAgingTable } from "@/components/business/ar-ap-aging-table";
import { AreaChart } from "@/components/business/area-chart";
import { AsyncTaskCenter } from "@/components/business/async-task-center";
import { AsyncTaskTrigger } from "@/components/business/async-task-trigger";
import { AttachmentList } from "@/components/business/attachment-list";
import { AttachmentPreview } from "@/components/business/attachment-preview";
import { AttachmentUploader } from "@/components/business/attachment-uploader";
import { AttendanceCalendar } from "@/components/business/attendance-calendar";
import { AudienceSegmentBuilder } from "@/components/business/audience-segment-builder";
import { AuditLog } from "@/components/business/audit-log";
import { AuditSidebar } from "@/components/business/audit-sidebar";
import { AuditTrailDiff } from "@/components/business/audit-trail-diff";
import { AuthGuard } from "@/components/business/auth-guard";
import { AvatarGroup } from "@/components/business/avatar-group";
import { BadgeDelta } from "@/components/business/badge-delta";
import { BarChart } from "@/components/business/bar-chart";
import { BarListCard } from "@/components/business/bar-list-card";
import { BarList } from "@/components/business/bar-list";
import { BatchGenealogyTree } from "@/components/business/batch-genealogy-tree";
import { BatchPrintDialog } from "@/components/business/batch-print-dialog";
import { BatchSelector } from "@/components/business/batch-selector";
import { BillFooter } from "@/components/business/bill-footer";
import { BillHeader } from "@/components/business/bill-header";
import { BillPage } from "@/components/business/bill-page";
import { BillPrintTemplate } from "@/components/business/bill-print-template";
import { BillStatusBar } from "@/components/business/bill-status-bar";
import { BillTimeline } from "@/components/business/bill-timeline";
import { BillTodoList } from "@/components/business/bill-todo-list";
import { BizStatusTag } from "@/components/business/biz-status-tag";
import { BOMTreeEditor as BomTreeEditor } from "@/components/business/bom-tree-editor";
import { BrowseDialog } from "@/components/business/browse-dialog";
import { BudgetAllocator } from "@/components/business/budget-allocator";
import { BudgetOverview } from "@/components/business/budget-overview";
import { BudgetPacingCard } from "@/components/business/budget-pacing-card";
import { BulkActionsToolbar } from "@/components/business/bulk-actions-toolbar";
import { BulkImportWizard } from "@/components/business/bulk-import-wizard";
import { CalendarView } from "@/components/business/calendar-view";
import { Callout } from "@/components/business/callout";
import { CampaignCalendar } from "@/components/business/campaign-calendar";
import { CampaignCard } from "@/components/business/campaign-card";
import { CampaignStatusTag } from "@/components/business/campaign-status-tag";
import { CategoryBar } from "@/components/business/category-bar";
import { ChannelPicker } from "@/components/business/channel-picker";
import { ChartCard } from "@/components/business/chart-card";
import { ChartSuite } from "@/components/business/chart-suite";
import { LineChart as Chart } from "@/components/business/chart";
import { ChatAgentStatus } from "@/components/business/chat-agent-status";
import { ChatArtifactPanel } from "@/components/business/chat-artifact-panel";
import { ChatBranch } from "@/components/business/chat-branch";
import { ChatCardMessage } from "@/components/business/chat-card-message";
import { ChatCodeBlock } from "@/components/business/chat-code-block";
import { ChatCommandMenu } from "@/components/business/chat-command-menu";
import { ChatContextPanel } from "@/components/business/chat-context-panel";
import { ChatConversationSearch } from "@/components/business/chat-conversation-search";
import { ChatConversation } from "@/components/business/chat-conversation";
import { ChatFeedback } from "@/components/business/chat-feedback";
import { ChatHeader } from "@/components/business/chat-header";
import { ChatImageGallery } from "@/components/business/chat-image-gallery";
import { ChatInputToolbar } from "@/components/business/chat-input-toolbar";
import { ChatMarkdownRenderer } from "@/components/business/chat-markdown-renderer";
import { ChatMentionPicker } from "@/components/business/chat-mention-picker";
import { ChatMessageActions } from "@/components/business/chat-message-actions";
import { ChatMessageBubble } from "@/components/business/chat-message-bubble";
import { ChatMessageGroup } from "@/components/business/chat-message-group";
import { ChatMessageInput } from "@/components/business/chat-message-input";
import { ChatModelSwitcher } from "@/components/business/chat-model-switcher";
import { ChatSharedLink } from "@/components/business/chat-shared-link";
import { ChatShell } from "@/components/business/chat-shell";
import { ChatSidebar } from "@/components/business/chat-sidebar";
import { ChatStreamingText } from "@/components/business/chat-streaming-text";
import { ChatSuggestReplies } from "@/components/business/chat-suggest-replies";
import { ChatThinkingBlock } from "@/components/business/chat-thinking-block";
import { ChatToolCallBlock } from "@/components/business/chat-tool-call-block";
import { ChatVoiceMessage } from "@/components/business/chat-voice-message";
import { CheckoutBar } from "@/components/business/checkout-bar";
import { Chip } from "@/components/business/chip";
import { CityBrowse } from "@/components/business/city-browse";
import { CodeBlock } from "@/components/business/code-block";
import { CodeEditor } from "@/components/business/code-editor";
import { ColorBoard } from "@/components/business/color-board";
import { ColorTag } from "@/components/business/color-tag";
import { CommandPalette } from "@/components/business/command-palette";
import { CommissionCalculator } from "@/components/business/commission-calculator";
import { CompanyBrowse } from "@/components/business/company-browse";
import { CompanyPicker } from "@/components/business/company-picker";
import { ComplianceChecklist } from "@/components/business/compliance-checklist";
import { ConfirmDialog } from "@/components/business/confirm-dialog";
import { ContractTemplate } from "@/components/business/contract-template";
import { CookieBanner } from "@/components/business/cookie-banner";
import { CostCenterPicker } from "@/components/business/cost-center-picker";
import { CouponCard } from "@/components/business/coupon-card";
import { CreativePreview } from "@/components/business/creative-preview";
import { CronEditor } from "@/components/business/cron-editor";
import { CrudPage } from "@/components/business/crud-page";
import { CrudToolbar } from "@/components/business/crud-toolbar";
import { Customer360Card } from "@/components/business/customer-360-card";
import { CustomerBrowse } from "@/components/business/customer-browse";
import { CustomerPicker } from "@/components/business/customer-picker";
import { DashboardCanvas } from "@/components/business/dashboard-canvas";
import { DashboardDesigner } from "@/components/business/dashboard-designer";
import { DashboardGrid } from "@/components/business/dashboard-grid";
import { DataTable } from "@/components/business/data-table";
import { DateRangePicker } from "@/components/business/date-range-picker";
import { DeltaBar } from "@/components/business/delta-bar";
import { DepartmentPicker } from "@/components/business/department-picker";
import { DictSelect } from "@/components/business/dict-select";
import { DiffViewerTable } from "@/components/business/diff-viewer-table";
import { DiffViewer } from "@/components/business/diff-viewer";
import { DistributorPicker } from "@/components/business/distributor-picker";
import { DockPanel } from "@/components/business/dock-panel";
import { DonutCard } from "@/components/business/donut-card";
import { DonutChart } from "@/components/business/donut-chart";
import { DynamicFormBuilder } from "@/components/business/dynamic-form-builder";
import { EditToolbar } from "@/components/business/edit-toolbar";
import { EditableTreeTable } from "@/components/business/editable-tree-table";
import { EmployeePicker } from "@/components/business/employee-picker";
import { EquipmentCard } from "@/components/business/equipment-card";
import { ErrorBoundary } from "@/components/business/error-boundary";
import { ErrorPage } from "@/components/business/error-page";
import { ExpenseLineEditor } from "@/components/business/expense-line-editor";
import { ExperimentSummary } from "@/components/business/experiment-summary";
import { ExportButton } from "@/components/business/export-button";
import { FeatureTour } from "@/components/business/feature-tour";
import { FeeTypeBrowse } from "@/components/business/fee-type-browse";
import { FieldMask } from "@/components/business/field-mask";
import { FileCard } from "@/components/business/file-card";
import { FileUploadManager } from "@/components/business/file-upload-manager";
import { FilterBar } from "@/components/business/filter-bar";
import { FilterBuilder } from "@/components/business/filter-builder";
import { FlowTracker } from "@/components/business/flow-tracker";
import { Forbidden } from "@/components/business/forbidden";
import { FormDesignerRuntime } from "@/components/business/form-designer-runtime";
import { FormDesigner } from "@/components/business/form-designer";
import { FormField } from "@/components/business/form-field";
import { FormWizard } from "@/components/business/form-wizard";
import { FormulaEditor } from "@/components/business/formula-editor";
import { FunnelChart } from "@/components/business/funnel-chart";
import { GanttChartPro } from "@/components/business/gantt-chart-pro";
import { GanttChart } from "@/components/business/gantt-chart";
import { GaugeChart } from "@/components/business/gauge-chart";
import { Gauge } from "@/components/business/gauge";
import { GlobalLoading } from "@/components/business/global-loading";
import { HeatmapCalendar } from "@/components/business/heatmap-calendar";
import { HeatmapChart } from "@/components/business/heatmap-chart";
import { I18nFormField } from "@/components/business/i18n-form-field";
import { ImMessage } from "@/components/business/im-message";
import { ImageGallery } from "@/components/business/image-gallery";
import { ImportDialog } from "@/components/business/import-dialog";
import { ImportErrorTable } from "@/components/business/import-error-table";
import { ImportMappingWizard } from "@/components/business/import-mapping-wizard";
import { InlineEdit } from "@/components/business/inline-edit";
import { InventoryAlertList } from "@/components/business/inventory-alert-list";
import { InventorySnapshot } from "@/components/business/inventory-snapshot";
import { InviteLink } from "@/components/business/invite-link";
import { InvoiceManager } from "@/components/business/invoice-manager";
import { InvoiceSummary } from "@/components/business/invoice-summary";
import { IotSensorGrid } from "@/components/business/iot-sensor-grid";
import { JournalEntryEditor } from "@/components/business/journal-entry-editor";
import { JsonEditor } from "@/components/business/json-editor";
import { JsonViewer } from "@/components/business/json-viewer";
import { KanbanBoard } from "@/components/business/kanban-board";
import { KanbanColumn } from "@/components/business/kanban-column";
import { KPICard as KpiCard } from "@/components/business/kpi-card";
import { LabelDesigner } from "@/components/business/label-designer";
import { LanguageSwitcher } from "@/components/business/language-switcher";
import { LeadPipelineBoard } from "@/components/business/lead-pipeline-board";
import { LeaveRequestForm } from "@/components/business/leave-request-form";
import { LineChart } from "@/components/business/line-chart";
import { LineEditor } from "@/components/business/line-editor";
import { LoadingPage } from "@/components/business/loading-page";
import { MaintenanceLog } from "@/components/business/maintenance-log";
import { MapChart } from "@/components/business/map-chart";
import { MapMarkerCluster as MapMarker } from "@/components/business/map-marker";
import { MapTrack } from "@/components/business/map-track";
import { MapView } from "@/components/business/map-view";
import { MarkdownEditor } from "@/components/business/markdown-editor";
import { MarketingActivityForm } from "@/components/business/marketing-activity-form";
import { MasterEditTemplate } from "@/components/business/master-edit-template";
import { MasterListTemplate } from "@/components/business/master-list-template";
import { MediaRecorderComponent as MediaRecorder } from "@/components/business/media-recorder";
import { MeetingRoomBooking } from "@/components/business/meeting-room-booking";
import { MessageList } from "@/components/business/message-list";
import { MetricTrend } from "@/components/business/metric-trend";
import { MobileActionSheet } from "@/components/business/mobile-action-sheet";
import { MobileCamera } from "@/components/business/mobile-camera";
import { MobileGeolocation } from "@/components/business/mobile-geolocation";
import { MobileInfiniteScroll } from "@/components/business/mobile-infinite-scroll";
import { MobileListItem } from "@/components/business/mobile-list-item";
import { MobilePageShell } from "@/components/business/mobile-page-shell";
import { MobilePicker } from "@/components/business/mobile-picker";
import { MobileQrCodeScanner as MobileQrcodeScanner } from "@/components/business/mobile-qrcode-scanner";
import { MobileSignature } from "@/components/business/mobile-signature";
import { MobileTabBar } from "@/components/business/mobile-tab-bar";
import { MultiCurrencyInput } from "@/components/business/multi-currency-input";
import { MultiSelect } from "@/components/business/multi-select";
import { NotificationCenter } from "@/components/business/notification-center";
import { NotificationRuleBuilder } from "@/components/business/notification-rule-builder";
import { OaBridge } from "@/components/business/oa-bridge";
import { OeeDashboard } from "@/components/business/oee-dashboard";
import { OperationLog } from "@/components/business/operation-log";
import { OrderLineEditor } from "@/components/business/order-line-editor";
import { OrgChart } from "@/components/business/org-chart";
import { OverviewPage } from "@/components/business/overview-page";
import { PageHeader } from "@/components/business/page-header";
import { PasteUpload } from "@/components/business/paste-upload";
import { PaymentMethodSelector } from "@/components/business/payment-method-selector";
import { PaymentResult } from "@/components/business/payment-result";
import { PaymentSchedule } from "@/components/business/payment-schedule";
import { PDFViewer as PdfViewer } from "@/components/business/pdf-viewer";
import { PerformanceRankTable } from "@/components/business/performance-rank-table";
import { PermissionButton } from "@/components/business/permission-button";
import { PermissionMatrix } from "@/components/business/permission-matrix";
import { PermissionWrapper } from "@/components/business/permission-wrapper";
import { PhotoAudit } from "@/components/business/photo-audit";
import { PieChart } from "@/components/business/pie-chart";
import { PivotTable } from "@/components/business/pivot-table";
import { PolicyLineEditor } from "@/components/business/policy-line-editor";
import { PoolTrackerTable } from "@/components/business/pool-tracker-table";
import { PreferencePanel } from "@/components/business/preference-panel";
import { PriceAdjustBrowse } from "@/components/business/price-adjust-browse";
import { PrintButton } from "@/components/business/print-button";
import { PrintService } from "@/components/business/print-service";
import { PrintTemplateBuilder } from "@/components/business/print-template-builder";
import { ProductBrowse } from "@/components/business/product-browse";
import { ProductCategoryPicker } from "@/components/business/product-category-picker";
import { PromotionRuleCard } from "@/components/business/promotion-rule-card";
import { PromotionRuleEditor } from "@/components/business/promotion-rule-editor";
import { PromptDialog } from "@/components/business/prompt-dialog";
import { PurchaseOrderEditor } from "@/components/business/purchase-order-editor";
import { QualityInspectionForm } from "@/components/business/quality-inspection-form";
import { QuickEntryGrid } from "@/components/business/quick-entry-grid";
import { QuotationLineEditor } from "@/components/business/quotation-line-editor";
import { RadarChart } from "@/components/business/radar-chart";
import { RadialChart } from "@/components/business/radial-chart";
import { RebutNodeSelect } from "@/components/business/rebut-node-select";
import { ReconciliationLineEditor } from "@/components/business/reconciliation-line-editor";
import { ReconciliationSummary } from "@/components/business/reconciliation-summary";
import { RedPacket } from "@/components/business/red-packet";
import { RegionPicker } from "@/components/business/region-picker";
import { RemoteSelect } from "@/components/business/remote-select";
import { ReportBuilder } from "@/components/business/report-builder";
import { ResourceSchedule } from "@/components/business/resource-schedule";
import { ResponsivePreview } from "@/components/business/responsive-preview";
import { RichTextEditor } from "@/components/business/rich-text-editor";
import { RoleAssignment } from "@/components/business/role-assignment";
import { RuleEditor } from "@/components/business/rule-editor";
import { SalesOrderBrowse } from "@/components/business/sales-order-browse";
import { SalesTargetEditor } from "@/components/business/sales-target-editor";
import { SankeyChart } from "@/components/business/sankey-chart";
import { SavedFilters } from "@/components/business/saved-filters";
import { ScatterChart } from "@/components/business/scatter-chart";
import { SealStampRegistry } from "@/components/business/seal-stamp-registry";
import { SearchTable } from "@/components/business/search-table";
import { SerialNumberManager } from "@/components/business/serial-number-manager";
import { SettlementStatusTag } from "@/components/business/settlement-status-tag";
import { ShiftCalendar } from "@/components/business/shift-calendar";
import { ShippingWayBrowse } from "@/components/business/shipping-way-browse";
import { SignActionButton } from "@/components/business/sign-action-button";
import { SkuPicker } from "@/components/business/sku-picker";
import { SocialShare } from "@/components/business/social-share";
import { SparkChart } from "@/components/business/spark-chart";
import { SPCControlChart as SpcControlChart } from "@/components/business/spc-control-chart";
import { SqlEditor } from "@/components/business/sql-editor";
import { StatCardRow } from "@/components/business/stat-card-row";
import { StatCardWithDelta } from "@/components/business/stat-card-with-delta";
import { StatCardWithSparkline } from "@/components/business/stat-card-with-sparkline";
import { StatCard } from "@/components/business/stat-card";
import { StatusBadge } from "@/components/business/status-badge";
import { StatusTag } from "@/components/business/status-tag";
import { StockTransferDialog } from "@/components/business/stock-transfer-dialog";
import { SubformTabs } from "@/components/business/subform-tabs";
import { SupplierScorecard } from "@/components/business/supplier-scorecard";
import { TabCrudPage } from "@/components/business/tab-crud-page";
import { TabPin } from "@/components/business/tab-pin";
import { TargetProgress } from "@/components/business/target-progress";
import { TaskHistory } from "@/components/business/task-history";
import { TaskListTable } from "@/components/business/task-list-table";
import { TaskProgress } from "@/components/business/task-progress";
import { TaxDetailTable } from "@/components/business/tax-detail-table";
import { TemplateDownload } from "@/components/business/template-download";
import { TerritoryMap } from "@/components/business/territory-map";
import { ThemeToggle } from "@/components/business/theme-toggle";
import { TimelineView } from "@/components/business/timeline-view";
import { TodoListTable } from "@/components/business/todo-list-table";
import { Tracking } from "@/components/business/tracking";
import { TreeCrudPage } from "@/components/business/tree-crud-page";
import { TreeTable } from "@/components/business/tree-table";
import { TreemapChart } from "@/components/business/treemap-chart";
import { UnitConverter } from "@/components/business/unit-converter";
import { UserMenu } from "@/components/business/user-menu";
import { UtmBuilder } from "@/components/business/utm-builder";
import { VehicleBooking } from "@/components/business/vehicle-booking";
import { VersionHistory } from "@/components/business/version-history";
import { WarehouseBrowse } from "@/components/business/warehouse-browse";
import { WarehousePicker } from "@/components/business/warehouse-picker";
import { WaterfallChart } from "@/components/business/waterfall-chart";
import { WorkOrderCard } from "@/components/business/work-order-card";
import { WorkflowDesigner } from "@/components/business/workflow-designer";
import { WorkflowPreview } from "@/components/business/workflow-preview";
import { WriteoffBrowse } from "@/components/business/writeoff-browse";
import { WriteoffFlow } from "@/components/business/writeoff-flow";

export const componentMap: Record<string, React.ComponentType<any>> = {
  Accordion,
  Affix,
  AlertDialog,
  Alert,
  Anchor,
  AspectRatio,
  AudioPlayer,
  Autocomplete,
  Avatar,
  BackTop,
  Badge,
  BarcodeDisplay,
  Breadcrumb,
  BrowseInput,
  Button,
  Calendar,
  Card,
  Carousel,
  Cascader,
  ChatInput,
  ChatMessage,
  Checkbox,
  Collapsible,
  ColorPicker,
  Combobox,
  Command,
  ConfigProvider,
  ContextMenu,
  Countdown,
  DatePicker,
  DepartmentBrowse,
  Descriptions,
  Dialog,
  Direction,
  Divider,
  Dot,
  Drawer,
  DropdownMenu,
  EmptyState,
  Fab,
  FileUpload,
  Flex,
  FormGrid,
  FormList,
  FormSection,
  Form,
  FullscreenToggle,
  GridLayout,
  Grid,
  HoverCard,
  IconPicker,
  Icon,
  ImageViewer,
  Image,
  InfiniteScroll,
  InputGroup,
  InputNumber,
  InputSearch,
  Input,
  Kbd,
  KeyboardShortcutDialog,
  KeyboardShortcut,
  KpiPanel,
  Label,
  List,
  Masonry,
  Mentions,
  Menu,
  Menubar,
  MessageProvider,
  Message,
  MobilePullRefresh,
  MobileSwipeAction,
  ModalProvider,
  NativeSelect,
  NavigationMenu,
  Notification,
  NumberTicker,
  OtpField,
  PageContainer,
  Pagination,
  Popconfirm,
  Popover,
  Progress,
  QrcodeDisplay,
  Qrcode,
  RadioGroup,
  Rating,
  Resizable,
  Result,
  SchemaForm,
  ScrollArea,
  SegmentedControl,
  Select,
  Separator,
  SequenceInput,
  SequencePreview,
  Sheet,
  Sidebar,
  SignaturePad,
  Skeleton,
  Slider,
  Sonner,
  Space,
  Spin,
  Spinner,
  SplitButton,
  SplitPane,
  Statistic,
  Stepper,
  Switch,
  Table,
  Tabs,
  Tag,
  TagsInput,
  Textarea,
  TimePicker,
  Timeline,
  ToggleGroup,
  Toggle,
  Tooltip,
  Tour,
  Transfer,
  TreeSelect,
  TreeView,
  Typography,
  UserBrowse,
  VideoPlayer,
  VirtualList,
  VirtualTable,
  Watermark,
  WithPermission,
  AdminBreadcrumb,
  AdminHeader,
  AdminShell,
  AdminSider,
  AdminTabs,
  AppShell,
  ArticleLayout,
  AuthLayout,
  BlankLayout,
  ChatLayout,
  DashboardLayout,
  DetailLayout,
  DialogFormBody,
  EmbedLayout,
  ErrorLayout,
  MasterDetailLayout,
  MasterDetailTabs,
  NavigationTabsBar,
  PrintLayout,
  PrintTemplateLayout,
  PublicLayout,
  RegionLayout,
  SplitScreen,
  TopBar,
  WizardLayout,
  AccountBalance,
  ActivityFeed,
  AddressPicker,
  AdvancedDataTable,
  AdvancedSearch,
  AnnouncementBanner,
  AnnouncementCard,
  ApplicationForm,
  ApprovalActionBar,
  ApprovalFlow,
  ApprovalTimeline,
  ArApAgingTable,
  AreaChart,
  AsyncTaskCenter,
  AsyncTaskTrigger,
  AttachmentList,
  AttachmentPreview,
  AttachmentUploader,
  AttendanceCalendar,
  AudienceSegmentBuilder,
  AuditLog,
  AuditSidebar,
  AuditTrailDiff,
  AuthGuard,
  AvatarGroup,
  BadgeDelta,
  BarChart,
  BarListCard,
  BarList,
  BatchGenealogyTree,
  BatchPrintDialog,
  BatchSelector,
  BillFooter,
  BillHeader,
  BillPage,
  BillPrintTemplate,
  BillStatusBar,
  BillTimeline,
  BillTodoList,
  BizStatusTag,
  BomTreeEditor,
  BrowseDialog,
  BudgetAllocator,
  BudgetOverview,
  BudgetPacingCard,
  BulkActionsToolbar,
  BulkImportWizard,
  CalendarView,
  Callout,
  CampaignCalendar,
  CampaignCard,
  CampaignStatusTag,
  CategoryBar,
  ChannelPicker,
  ChartCard,
  ChartSuite,
  Chart,
  ChatAgentStatus,
  ChatArtifactPanel,
  ChatBranch,
  ChatCardMessage,
  ChatCodeBlock,
  ChatCommandMenu,
  ChatContextPanel,
  ChatConversationSearch,
  ChatConversation,
  ChatFeedback,
  ChatHeader,
  ChatImageGallery,
  ChatInputToolbar,
  ChatMarkdownRenderer,
  ChatMentionPicker,
  ChatMessageActions,
  ChatMessageBubble,
  ChatMessageGroup,
  ChatMessageInput,
  ChatModelSwitcher,
  ChatSharedLink,
  ChatShell,
  ChatSidebar,
  ChatStreamingText,
  ChatSuggestReplies,
  ChatThinkingBlock,
  ChatToolCallBlock,
  ChatVoiceMessage,
  CheckoutBar,
  Chip,
  CityBrowse,
  CodeBlock,
  CodeEditor,
  ColorBoard,
  ColorTag,
  CommandPalette,
  CommissionCalculator,
  CompanyBrowse,
  CompanyPicker,
  ComplianceChecklist,
  ConfirmDialog,
  ContractTemplate,
  CookieBanner,
  CostCenterPicker,
  CouponCard,
  CreativePreview,
  CronEditor,
  CrudPage,
  CrudToolbar,
  Customer360Card,
  CustomerBrowse,
  CustomerPicker,
  DashboardCanvas,
  DashboardDesigner,
  DashboardGrid,
  DataTable,
  DateRangePicker,
  DeltaBar,
  DepartmentPicker,
  DictSelect,
  DiffViewerTable,
  DiffViewer,
  DistributorPicker,
  DockPanel,
  DonutCard,
  DonutChart,
  DynamicFormBuilder,
  EditToolbar,
  EditableTreeTable,
  EmployeePicker,
  EquipmentCard,
  ErrorBoundary,
  ErrorPage,
  ExpenseLineEditor,
  ExperimentSummary,
  ExportButton,
  FeatureTour,
  FeeTypeBrowse,
  FieldMask,
  FileCard,
  FileUploadManager,
  FilterBar,
  FilterBuilder,
  FlowTracker,
  Forbidden,
  FormDesignerRuntime,
  FormDesigner,
  FormField,
  FormWizard,
  FormulaEditor,
  FunnelChart,
  GanttChartPro,
  GanttChart,
  GaugeChart,
  Gauge,
  GlobalLoading,
  HeatmapCalendar,
  HeatmapChart,
  I18nFormField,
  ImMessage,
  ImageGallery,
  ImportDialog,
  ImportErrorTable,
  ImportMappingWizard,
  InlineEdit,
  InventoryAlertList,
  InventorySnapshot,
  InviteLink,
  InvoiceManager,
  InvoiceSummary,
  IotSensorGrid,
  JournalEntryEditor,
  JsonEditor,
  JsonViewer,
  KanbanBoard,
  KanbanColumn,
  KpiCard,
  LabelDesigner,
  LanguageSwitcher,
  LeadPipelineBoard,
  LeaveRequestForm,
  LineChart,
  LineEditor,
  LoadingPage,
  MaintenanceLog,
  MapChart,
  MapMarker,
  MapTrack,
  MapView,
  MarkdownEditor,
  MarketingActivityForm,
  MasterEditTemplate,
  MasterListTemplate,
  MediaRecorder,
  MeetingRoomBooking,
  MessageList,
  MetricTrend,
  MobileActionSheet,
  MobileCamera,
  MobileGeolocation,
  MobileInfiniteScroll,
  MobileListItem,
  MobilePageShell,
  MobilePicker,
  MobileQrcodeScanner,
  MobileSignature,
  MobileTabBar,
  MultiCurrencyInput,
  MultiSelect,
  NotificationCenter,
  NotificationRuleBuilder,
  OaBridge,
  OeeDashboard,
  OperationLog,
  OrderLineEditor,
  OrgChart,
  OverviewPage,
  PageHeader,
  PasteUpload,
  PaymentMethodSelector,
  PaymentResult,
  PaymentSchedule,
  PdfViewer,
  PerformanceRankTable,
  PermissionButton,
  PermissionMatrix,
  PermissionWrapper,
  PhotoAudit,
  PieChart,
  PivotTable,
  PolicyLineEditor,
  PoolTrackerTable,
  PreferencePanel,
  PriceAdjustBrowse,
  PrintButton,
  PrintService,
  PrintTemplateBuilder,
  ProductBrowse,
  ProductCategoryPicker,
  PromotionRuleCard,
  PromotionRuleEditor,
  PromptDialog,
  PurchaseOrderEditor,
  QualityInspectionForm,
  QuickEntryGrid,
  QuotationLineEditor,
  RadarChart,
  RadialChart,
  RebutNodeSelect,
  ReconciliationLineEditor,
  ReconciliationSummary,
  RedPacket,
  RegionPicker,
  RemoteSelect,
  ReportBuilder,
  ResourceSchedule,
  ResponsivePreview,
  RichTextEditor,
  RoleAssignment,
  RuleEditor,
  SalesOrderBrowse,
  SalesTargetEditor,
  SankeyChart,
  SavedFilters,
  ScatterChart,
  SealStampRegistry,
  SearchTable,
  SerialNumberManager,
  SettlementStatusTag,
  ShiftCalendar,
  ShippingWayBrowse,
  SignActionButton,
  SkuPicker,
  SocialShare,
  SparkChart,
  SpcControlChart,
  SqlEditor,
  StatCardRow,
  StatCardWithDelta,
  StatCardWithSparkline,
  StatCard,
  StatusBadge,
  StatusTag,
  StockTransferDialog,
  SubformTabs,
  SupplierScorecard,
  TabCrudPage,
  TabPin,
  TargetProgress,
  TaskHistory,
  TaskListTable,
  TaskProgress,
  TaxDetailTable,
  TemplateDownload,
  TerritoryMap,
  ThemeToggle,
  TimelineView,
  TodoListTable,
  Tracking,
  TreeCrudPage,
  TreeTable,
  TreemapChart,
  UnitConverter,
  UserMenu,
  UtmBuilder,
  VehicleBooking,
  VersionHistory,
  WarehouseBrowse,
  WarehousePicker,
  WaterfallChart,
  WorkOrderCard,
  WorkflowDesigner,
  WorkflowPreview,
  WriteoffBrowse,
  WriteoffFlow,
};
