// Auto-generated by scripts/generate-component-loader.mjs. Do not edit manually.
// Lazy-loading component map. Each entry is a separate `dynamic()` call
// so Turbopack code-splits each component into its own chunk.
// No component code is loaded until its entry is actually rendered.

"use client";

import dynamic from "next/dynamic";

export const componentLoaders: Record<string, React.ComponentType<any>> = {
  Accordion: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.Accordion,
      })),
    { ssr: false },
  ),
  Affix: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Affix })),
    { ssr: false },
  ),
  AlertDialog: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.AlertDialog,
      })),
    { ssr: false },
  ),
  Alert: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Alert })),
    { ssr: false },
  ),
  Anchor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Anchor })),
    { ssr: false },
  ),
  AspectRatio: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.AspectRatio,
      })),
    { ssr: false },
  ),
  AudioPlayer: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.AudioPlayer,
      })),
    { ssr: false },
  ),
  Autocomplete: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.Autocomplete,
      })),
    { ssr: false },
  ),
  Avatar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Avatar })),
    { ssr: false },
  ),
  BackTop: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.BackTop })),
    { ssr: false },
  ),
  Badge: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Badge })),
    { ssr: false },
  ),
  BarcodeDisplay: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.BarcodeDisplay,
      })),
    { ssr: false },
  ),
  Breadcrumb: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.Breadcrumb,
      })),
    { ssr: false },
  ),
  BrowseInput: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.BrowseInput,
      })),
    { ssr: false },
  ),
  Button: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Button })),
    { ssr: false },
  ),
  Calendar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Calendar })),
    { ssr: false },
  ),
  Card: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Card })),
    { ssr: false },
  ),
  Carousel: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Carousel })),
    { ssr: false },
  ),
  Cascader: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Cascader })),
    { ssr: false },
  ),
  ChatInput: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.ChatInput,
      })),
    { ssr: false },
  ),
  ChatMessage: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.ChatMessage,
      })),
    { ssr: false },
  ),
  Checkbox: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Checkbox })),
    { ssr: false },
  ),
  Collapsible: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.Collapsible,
      })),
    { ssr: false },
  ),
  ColorPicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.ColorPicker,
      })),
    { ssr: false },
  ),
  Combobox: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Combobox })),
    { ssr: false },
  ),
  Command: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Command })),
    { ssr: false },
  ),
  ConfigProvider: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.ConfigProvider,
      })),
    { ssr: false },
  ),
  ContextMenu: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.ContextMenu,
      })),
    { ssr: false },
  ),
  Countdown: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.Countdown,
      })),
    { ssr: false },
  ),
  DatePicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.DatePicker,
      })),
    { ssr: false },
  ),
  DepartmentBrowse: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.DepartmentBrowse,
      })),
    { ssr: false },
  ),
  Descriptions: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.Descriptions,
      })),
    { ssr: false },
  ),
  Dialog: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Dialog })),
    { ssr: false },
  ),
  Direction: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.Direction,
      })),
    { ssr: false },
  ),
  Divider: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Divider })),
    { ssr: false },
  ),
  Dot: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Dot })),
    { ssr: false },
  ),
  Drawer: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Drawer })),
    { ssr: false },
  ),
  DropdownMenu: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.DropdownMenu,
      })),
    { ssr: false },
  ),
  EmptyState: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.EmptyState,
      })),
    { ssr: false },
  ),
  Fab: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Fab })),
    { ssr: false },
  ),
  FileUpload: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.FileUpload,
      })),
    { ssr: false },
  ),
  Flex: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Flex })),
    { ssr: false },
  ),
  FormGrid: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.FormGrid,
      })),
    { ssr: false },
  ),
  FormList: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.FormList,
      })),
    { ssr: false },
  ),
  FormSection: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.FormSection,
      })),
    { ssr: false },
  ),
  Form: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Form })),
    { ssr: false },
  ),
  FullscreenToggle: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.FullscreenToggle,
      })),
    { ssr: false },
  ),
  GridLayout: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.GridLayout,
      })),
    { ssr: false },
  ),
  Grid: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.GridLayout,
      })),
    { ssr: false },
  ),
  HoverCard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.HoverCard,
      })),
    { ssr: false },
  ),
  IconPicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.IconPicker,
      })),
    { ssr: false },
  ),
  Icon: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Icon })),
    { ssr: false },
  ),
  ImageViewer: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.ImageViewer,
      })),
    { ssr: false },
  ),
  Image: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Image })),
    { ssr: false },
  ),
  InfiniteScroll: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.InfiniteScroll,
      })),
    { ssr: false },
  ),
  InputGroup: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.InputGroup,
      })),
    { ssr: false },
  ),
  InputNumber: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.InputNumber,
      })),
    { ssr: false },
  ),
  InputSearch: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.InputSearch,
      })),
    { ssr: false },
  ),
  Input: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Input })),
    { ssr: false },
  ),
  Kbd: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Kbd })),
    { ssr: false },
  ),
  KeyboardShortcutDialog: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.KeyboardShortcutDialog,
      })),
    { ssr: false },
  ),
  KeyboardShortcut: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.KeyboardShortcut,
      })),
    { ssr: false },
  ),
  KpiPanel: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.KPIPanel,
      })),
    { ssr: false },
  ),
  Label: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Label })),
    { ssr: false },
  ),
  List: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.List })),
    { ssr: false },
  ),
  Masonry: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Masonry })),
    { ssr: false },
  ),
  Mentions: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Mentions })),
    { ssr: false },
  ),
  Menu: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Menu })),
    { ssr: false },
  ),
  Menubar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Menubar })),
    { ssr: false },
  ),
  MessageProvider: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.MessageProvider,
      })),
    { ssr: false },
  ),
  Message: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Message })),
    { ssr: false },
  ),
  MobilePullRefresh: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.MobilePullRefresh,
      })),
    { ssr: false },
  ),
  MobileSwipeAction: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.MobileSwipeAction,
      })),
    { ssr: false },
  ),
  ModalProvider: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.ModalProvider,
      })),
    { ssr: false },
  ),
  NativeSelect: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.NativeSelect,
      })),
    { ssr: false },
  ),
  NavigationMenu: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.NavigationMenu,
      })),
    { ssr: false },
  ),
  Notification: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.Notification,
      })),
    { ssr: false },
  ),
  NumberTicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.NumberTicker,
      })),
    { ssr: false },
  ),
  OtpField: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.OTPField,
      })),
    { ssr: false },
  ),
  PageContainer: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.PageContainer,
      })),
    { ssr: false },
  ),
  Pagination: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.Pagination,
      })),
    { ssr: false },
  ),
  Popconfirm: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.Popconfirm,
      })),
    { ssr: false },
  ),
  Popover: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Popover })),
    { ssr: false },
  ),
  Progress: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Progress })),
    { ssr: false },
  ),
  QrcodeDisplay: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.QRCodeDisplay,
      })),
    { ssr: false },
  ),
  Qrcode: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.QRCode })),
    { ssr: false },
  ),
  RadioGroup: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.RadioGroup,
      })),
    { ssr: false },
  ),
  Rating: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Rating })),
    { ssr: false },
  ),
  Resizable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.ResizablePanelGroup,
      })),
    { ssr: false },
  ),
  Result: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Result })),
    { ssr: false },
  ),
  SchemaForm: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.SchemaForm,
      })),
    { ssr: false },
  ),
  ScrollArea: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.ScrollArea,
      })),
    { ssr: false },
  ),
  SegmentedControl: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.SegmentedControl,
      })),
    { ssr: false },
  ),
  Select: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Select })),
    { ssr: false },
  ),
  Separator: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.Separator,
      })),
    { ssr: false },
  ),
  SequenceInput: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.SequenceInput,
      })),
    { ssr: false },
  ),
  SequencePreview: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.SequencePreview,
      })),
    { ssr: false },
  ),
  Sheet: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Sheet })),
    { ssr: false },
  ),
  Sidebar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Sidebar })),
    { ssr: false },
  ),
  SignaturePad: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.SignaturePad,
      })),
    { ssr: false },
  ),
  Skeleton: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Skeleton })),
    { ssr: false },
  ),
  Slider: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Slider })),
    { ssr: false },
  ),
  Sonner: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Toaster })),
    { ssr: false },
  ),
  Space: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Space })),
    { ssr: false },
  ),
  Spin: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Spin })),
    { ssr: false },
  ),
  Spinner: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Spinner })),
    { ssr: false },
  ),
  SplitButton: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.SplitButton,
      })),
    { ssr: false },
  ),
  SplitPane: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.SplitPane,
      })),
    { ssr: false },
  ),
  Statistic: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.Statistic,
      })),
    { ssr: false },
  ),
  Stepper: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Stepper })),
    { ssr: false },
  ),
  Switch: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Switch })),
    { ssr: false },
  ),
  Table: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Table })),
    { ssr: false },
  ),
  Tabs: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Tabs })),
    { ssr: false },
  ),
  Tag: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Tag })),
    { ssr: false },
  ),
  TagsInput: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.TagsInput,
      })),
    { ssr: false },
  ),
  Textarea: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Textarea })),
    { ssr: false },
  ),
  TimePicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.TimePicker,
      })),
    { ssr: false },
  ),
  Timeline: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Timeline })),
    { ssr: false },
  ),
  ToggleGroup: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.ToggleGroup,
      })),
    { ssr: false },
  ),
  Toggle: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Toggle })),
    { ssr: false },
  ),
  Tooltip: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Tooltip })),
    { ssr: false },
  ),
  Tour: dynamic(
    () => import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Tour })),
    { ssr: false },
  ),
  Transfer: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({ default: m.Transfer })),
    { ssr: false },
  ),
  TreeSelect: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.TreeSelect,
      })),
    { ssr: false },
  ),
  TreeView: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.TreeView,
      })),
    { ssr: false },
  ),
  Typography: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.Typography as any,
      })),
    { ssr: false },
  ) as any,
  UserBrowse: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.UserBrowse,
      })),
    { ssr: false },
  ),
  VideoPlayer: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.VideoPlayer,
      })),
    { ssr: false },
  ),
  VirtualList: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.VirtualList,
      })),
    { ssr: false },
  ),
  VirtualTable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.VirtualTable,
      })),
    { ssr: false },
  ),
  Watermark: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.Watermark,
      })),
    { ssr: false },
  ),
  WithPermission: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.WithPermission,
      })),
    { ssr: false },
  ),
  AdminBreadcrumb: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.AdminBreadcrumb,
      })),
    { ssr: false },
  ),
  AdminHeader: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.AdminHeader,
      })),
    { ssr: false },
  ),
  AdminShell: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.AdminShell,
      })),
    { ssr: false },
  ),
  AdminSider: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.AdminSider,
      })),
    { ssr: false },
  ),
  AdminTabs: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.AdminTabs,
      })),
    { ssr: false },
  ),
  AppShell: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.AppShell,
      })),
    { ssr: false },
  ),
  ArticleLayout: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.ArticleLayout,
      })),
    { ssr: false },
  ),
  AuthLayout: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.AuthLayout,
      })),
    { ssr: false },
  ),
  BlankLayout: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.BlankLayout,
      })),
    { ssr: false },
  ),
  ChatLayout: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.ChatLayout,
      })),
    { ssr: false },
  ),
  DashboardLayout: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.DashboardLayout,
      })),
    { ssr: false },
  ),
  DetailLayout: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.DetailLayout,
      })),
    { ssr: false },
  ),
  DialogFormBody: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.DialogFormBody,
      })),
    { ssr: false },
  ),
  EmbedLayout: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.EmbedLayout,
      })),
    { ssr: false },
  ),
  ErrorLayout: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.ErrorLayout,
      })),
    { ssr: false },
  ),
  MasterDetailLayout: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.MasterDetailLayout,
      })),
    { ssr: false },
  ),
  MasterDetailTabs: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.MasterDetailTabs,
      })),
    { ssr: false },
  ),
  NavigationTabsBar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.NavigationTabsBar,
      })),
    { ssr: false },
  ),
  PrintLayout: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.PrintLayout,
      })),
    { ssr: false },
  ),
  PrintTemplateLayout: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.PrintTemplateLayout,
      })),
    { ssr: false },
  ),
  PublicLayout: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.PublicLayout,
      })),
    { ssr: false },
  ),
  RegionLayout: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.RegionLayout,
      })),
    { ssr: false },
  ),
  SplitScreen: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.SplitScreen,
      })),
    { ssr: false },
  ),
  TopBar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.TopBar,
      })),
    { ssr: false },
  ),
  WizardLayout: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.WizardLayout,
      })),
    { ssr: false },
  ),
  AccountBalance: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AccountBalance,
      })),
    { ssr: false },
  ),
  ActivityFeed: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ActivityFeed,
      })),
    { ssr: false },
  ),
  AddressPicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AddressPicker,
      })),
    { ssr: false },
  ),
  AdvancedDataTable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AdvancedDataTable,
      })),
    { ssr: false },
  ),
  AdvancedSearch: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AdvancedSearch,
      })),
    { ssr: false },
  ),
  AnnouncementBanner: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AnnouncementBanner,
      })),
    { ssr: false },
  ),
  AnnouncementCard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AnnouncementCard,
      })),
    { ssr: false },
  ),
  ApplicationForm: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ApplicationForm,
      })),
    { ssr: false },
  ),
  ApprovalActionBar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ApprovalActionBar,
      })),
    { ssr: false },
  ),
  ApprovalFlow: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ApprovalFlow,
      })),
    { ssr: false },
  ),
  ApprovalTimeline: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ApprovalTimeline,
      })),
    { ssr: false },
  ),
  ArApAgingTable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ArApAgingTable,
      })),
    { ssr: false },
  ),
  AreaChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AreaChart,
      })),
    { ssr: false },
  ),
  AsyncTaskCenter: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AsyncTaskCenter,
      })),
    { ssr: false },
  ),
  AsyncTaskTrigger: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AsyncTaskTrigger,
      })),
    { ssr: false },
  ),
  AttachmentList: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AttachmentList,
      })),
    { ssr: false },
  ),
  AttachmentPreview: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AttachmentPreview,
      })),
    { ssr: false },
  ),
  AttachmentUploader: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AttachmentUploader,
      })),
    { ssr: false },
  ),
  AttendanceCalendar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AttendanceCalendar,
      })),
    { ssr: false },
  ),
  AudienceSegmentBuilder: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AudienceSegmentBuilder,
      })),
    { ssr: false },
  ),
  AuditLog: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AuditLog,
      })),
    { ssr: false },
  ),
  AuditSidebar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AuditSidebar,
      })),
    { ssr: false },
  ),
  AuditTrailDiff: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AuditTrailDiff,
      })),
    { ssr: false },
  ),
  AuthGuard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AuthGuard,
      })),
    { ssr: false },
  ),
  AvatarGroup: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AvatarGroup,
      })),
    { ssr: false },
  ),
  BadgeDelta: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BadgeDelta,
      })),
    { ssr: false },
  ),
  BarChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BarChart,
      })),
    { ssr: false },
  ),
  BarListCard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BarListCard,
      })),
    { ssr: false },
  ),
  BarList: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BarList,
      })),
    { ssr: false },
  ),
  BatchGenealogyTree: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BatchGenealogyTree,
      })),
    { ssr: false },
  ),
  BatchPrintDialog: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BatchPrintDialog,
      })),
    { ssr: false },
  ),
  BatchSelector: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BatchSelector,
      })),
    { ssr: false },
  ),
  BillFooter: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BillFooter,
      })),
    { ssr: false },
  ),
  BillHeader: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BillHeader,
      })),
    { ssr: false },
  ),
  BillPage: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BillPage,
      })),
    { ssr: false },
  ),
  BillPrintTemplate: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BillPrintTemplate,
      })),
    { ssr: false },
  ),
  BillStatusBar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BillStatusBar,
      })),
    { ssr: false },
  ),
  BillTimeline: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BillTimeline,
      })),
    { ssr: false },
  ),
  BillTodoList: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BillTodoList,
      })),
    { ssr: false },
  ),
  BizStatusTag: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BizStatusTag,
      })),
    { ssr: false },
  ),
  BomTreeEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BOMTreeEditor,
      })),
    { ssr: false },
  ),
  BrowseDialog: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BrowseDialog,
      })),
    { ssr: false },
  ),
  BudgetAllocator: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BudgetAllocator,
      })),
    { ssr: false },
  ),
  BudgetOverview: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BudgetOverview,
      })),
    { ssr: false },
  ),
  BudgetPacingCard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BudgetPacingCard,
      })),
    { ssr: false },
  ),
  BulkActionsToolbar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BulkActionsToolbar,
      })),
    { ssr: false },
  ),
  BulkImportWizard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BulkImportWizard,
      })),
    { ssr: false },
  ),
  CalendarView: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CalendarView,
      })),
    { ssr: false },
  ),
  Callout: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.Callout,
      })),
    { ssr: false },
  ),
  CampaignCalendar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CampaignCalendar,
      })),
    { ssr: false },
  ),
  CampaignCard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CampaignCard,
      })),
    { ssr: false },
  ),
  CampaignStatusTag: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CampaignStatusTag,
      })),
    { ssr: false },
  ),
  CategoryBar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CategoryBar,
      })),
    { ssr: false },
  ),
  ChannelPicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChannelPicker,
      })),
    { ssr: false },
  ),
  ChartCard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChartCard,
      })),
    { ssr: false },
  ),
  ChartSuite: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChartSuite,
      })),
    { ssr: false },
  ),
  Chart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.LineChart,
      })),
    { ssr: false },
  ),
  ChatAgentStatus: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatAgentStatus,
      })),
    { ssr: false },
  ),
  ChatArtifactPanel: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatArtifactPanel,
      })),
    { ssr: false },
  ),
  ChatBranch: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatBranch,
      })),
    { ssr: false },
  ),
  ChatCardMessage: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatCardMessage,
      })),
    { ssr: false },
  ),
  ChatCodeBlock: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatCodeBlock,
      })),
    { ssr: false },
  ),
  ChatCommandMenu: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatCommandMenu,
      })),
    { ssr: false },
  ),
  ChatContextPanel: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatContextPanel,
      })),
    { ssr: false },
  ),
  ChatConversationSearch: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatConversationSearch,
      })),
    { ssr: false },
  ),
  ChatConversation: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatConversation,
      })),
    { ssr: false },
  ),
  ChatFeedback: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatFeedback,
      })),
    { ssr: false },
  ),
  ChatHeader: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatHeader,
      })),
    { ssr: false },
  ),
  ChatImageGallery: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatImageGallery,
      })),
    { ssr: false },
  ),
  ChatInputToolbar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatInputToolbar,
      })),
    { ssr: false },
  ),
  ChatMarkdownRenderer: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatMarkdownRenderer,
      })),
    { ssr: false },
  ),
  ChatMentionPicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatMentionPicker,
      })),
    { ssr: false },
  ),
  ChatMessageActions: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatMessageActions,
      })),
    { ssr: false },
  ),
  ChatMessageBubble: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatMessageBubble,
      })),
    { ssr: false },
  ),
  ChatMessageGroup: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatMessageGroup,
      })),
    { ssr: false },
  ),
  ChatMessageInput: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatMessageInput,
      })),
    { ssr: false },
  ),
  ChatModelSwitcher: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatModelSwitcher,
      })),
    { ssr: false },
  ),
  ChatSharedLink: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatSharedLink,
      })),
    { ssr: false },
  ),
  ChatShell: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatShell,
      })),
    { ssr: false },
  ),
  ChatSidebar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatSidebar,
      })),
    { ssr: false },
  ),
  ChatStreamingText: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatStreamingText,
      })),
    { ssr: false },
  ),
  ChatSuggestReplies: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatSuggestReplies,
      })),
    { ssr: false },
  ),
  ChatThinkingBlock: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatThinkingBlock,
      })),
    { ssr: false },
  ),
  ChatToolCallBlock: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatToolCallBlock,
      })),
    { ssr: false },
  ),
  ChatVoiceMessage: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ChatVoiceMessage,
      })),
    { ssr: false },
  ),
  CheckoutBar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CheckoutBar,
      })),
    { ssr: false },
  ),
  Chip: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.Chip,
      })),
    { ssr: false },
  ),
  CityBrowse: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CityBrowse,
      })),
    { ssr: false },
  ),
  CodeBlock: dynamic(
    () =>
      import("@/components/business/code-block").then((m) => ({
        default: m.CodeBlock,
      })),
    { ssr: false },
  ),
  CodeEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CodeEditor,
      })),
    { ssr: false },
  ),
  ColorBoard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ColorBoard,
      })),
    { ssr: false },
  ),
  ColorTag: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ColorTag,
      })),
    { ssr: false },
  ),
  CommandPalette: dynamic(
    () =>
      import("@/components/business/command-palette").then((m) => ({
        default: m.CommandPalette,
      })),
    { ssr: false },
  ),
  CommissionCalculator: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CommissionCalculator,
      })),
    { ssr: false },
  ),
  CompanyBrowse: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CompanyBrowse,
      })),
    { ssr: false },
  ),
  CompanyPicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CompanyPicker,
      })),
    { ssr: false },
  ),
  ComplianceChecklist: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ComplianceChecklist,
      })),
    { ssr: false },
  ),
  ConfirmDialog: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ConfirmDialog,
      })),
    { ssr: false },
  ),
  ContractTemplate: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ContractTemplate,
      })),
    { ssr: false },
  ),
  CookieBanner: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CookieBanner,
      })),
    { ssr: false },
  ),
  CostCenterPicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CostCenterPicker,
      })),
    { ssr: false },
  ),
  CouponCard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CouponCard,
      })),
    { ssr: false },
  ),
  CreativePreview: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CreativePreview,
      })),
    { ssr: false },
  ),
  CronEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CronEditor,
      })),
    { ssr: false },
  ),
  CrudPage: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CrudPage,
      })),
    { ssr: false },
  ),
  CrudToolbar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CrudToolbar,
      })),
    { ssr: false },
  ),
  Customer360Card: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.Customer360Card,
      })),
    { ssr: false },
  ),
  CustomerBrowse: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CustomerBrowse,
      })),
    { ssr: false },
  ),
  CustomerPicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CustomerPicker,
      })),
    { ssr: false },
  ),
  DashboardCanvas: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.DashboardCanvas,
      })),
    { ssr: false },
  ),
  DashboardDesigner: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.DashboardDesigner,
      })),
    { ssr: false },
  ),
  DashboardGrid: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.DashboardGrid,
      })),
    { ssr: false },
  ),
  DataTable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.DataTable,
      })),
    { ssr: false },
  ),
  DateRangePicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.DateRangePicker,
      })),
    { ssr: false },
  ),
  DeltaBar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.DeltaBar,
      })),
    { ssr: false },
  ),
  DepartmentPicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.DepartmentPicker,
      })),
    { ssr: false },
  ),
  DictSelect: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.DictSelect,
      })),
    { ssr: false },
  ),
  DiffViewerTable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.DiffViewerTable,
      })),
    { ssr: false },
  ),
  DiffViewer: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.DiffViewer,
      })),
    { ssr: false },
  ),
  DistributorPicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.DistributorPicker,
      })),
    { ssr: false },
  ),
  DockPanel: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.DockPanel,
      })),
    { ssr: false },
  ),
  DonutCard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.DonutCard,
      })),
    { ssr: false },
  ),
  DonutChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.DonutChart,
      })),
    { ssr: false },
  ),
  DynamicFormBuilder: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.DynamicFormBuilder,
      })),
    { ssr: false },
  ),
  EditToolbar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.EditToolbar,
      })),
    { ssr: false },
  ),
  EditableTreeTable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.EditableTreeTable,
      })),
    { ssr: false },
  ),
  EmployeePicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.EmployeePicker,
      })),
    { ssr: false },
  ),
  EquipmentCard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.EquipmentCard,
      })),
    { ssr: false },
  ),
  ErrorBoundary: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ErrorBoundary,
      })),
    { ssr: false },
  ),
  ErrorPage: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ErrorPage,
      })),
    { ssr: false },
  ),
  ExpenseLineEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ExpenseLineEditor,
      })),
    { ssr: false },
  ),
  ExperimentSummary: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ExperimentSummary,
      })),
    { ssr: false },
  ),
  ExportButton: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ExportButton,
      })),
    { ssr: false },
  ),
  FeatureTour: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.FeatureTour,
      })),
    { ssr: false },
  ),
  FeeTypeBrowse: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.FeeTypeBrowse,
      })),
    { ssr: false },
  ),
  FieldMask: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.FieldMask,
      })),
    { ssr: false },
  ),
  FileCard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.FileCard,
      })),
    { ssr: false },
  ),
  FileUploadManager: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.FileUploadManager,
      })),
    { ssr: false },
  ),
  FilterBar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.FilterBar,
      })),
    { ssr: false },
  ),
  FilterBuilder: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.FilterBuilder,
      })),
    { ssr: false },
  ),
  FlowTracker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.FlowTracker,
      })),
    { ssr: false },
  ),
  Forbidden: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.Forbidden,
      })),
    { ssr: false },
  ),
  FormDesignerRuntime: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.FormDesignerRuntime,
      })),
    { ssr: false },
  ),
  FormDesigner: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.FormDesigner,
      })),
    { ssr: false },
  ),
  FormField: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.CrudFormField,
      })),
    { ssr: false },
  ),
  FormWizard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.FormWizard,
      })),
    { ssr: false },
  ),
  FormulaEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.FormulaEditor,
      })),
    { ssr: false },
  ),
  FunnelChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.FunnelChart,
      })),
    { ssr: false },
  ),
  GanttChartPro: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.GanttChartPro,
      })),
    { ssr: false },
  ),
  GanttChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.GanttChart,
      })),
    { ssr: false },
  ),
  GaugeChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.GaugeChart,
      })),
    { ssr: false },
  ),
  Gauge: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.Gauge,
      })),
    { ssr: false },
  ),
  GlobalLoading: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.GlobalLoadingProvider,
      })),
    { ssr: false },
  ),
  HeatmapCalendar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.HeatmapCalendar,
      })),
    { ssr: false },
  ),
  HeatmapChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.HeatmapChart,
      })),
    { ssr: false },
  ),
  I18nFormField: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.I18nFormField,
      })),
    { ssr: false },
  ),
  ImMessage: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ImMessage,
      })),
    { ssr: false },
  ),
  ImageGallery: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ImageGallery,
      })),
    { ssr: false },
  ),
  ImportDialog: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ImportDialog,
      })),
    { ssr: false },
  ),
  ImportErrorTable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ImportErrorTable,
      })),
    { ssr: false },
  ),
  ImportMappingWizard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ImportMappingWizard,
      })),
    { ssr: false },
  ),
  InlineEdit: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.InlineEdit,
      })),
    { ssr: false },
  ),
  InventoryAlertList: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.InventoryAlertList,
      })),
    { ssr: false },
  ),
  InventorySnapshot: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.InventorySnapshot,
      })),
    { ssr: false },
  ),
  InviteLink: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.InviteLink,
      })),
    { ssr: false },
  ),
  InvoiceManager: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.InvoiceManager,
      })),
    { ssr: false },
  ),
  InvoiceSummary: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.InvoiceSummary,
      })),
    { ssr: false },
  ),
  IotSensorGrid: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.IotSensorGrid,
      })),
    { ssr: false },
  ),
  JournalEntryEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.JournalEntryEditor,
      })),
    { ssr: false },
  ),
  JsonEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.JsonEditor,
      })),
    { ssr: false },
  ),
  JsonViewer: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.JsonViewer,
      })),
    { ssr: false },
  ),
  KanbanBoard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.KanbanBoard,
      })),
    { ssr: false },
  ),
  KanbanColumn: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.KanbanColumn,
      })),
    { ssr: false },
  ),
  KpiCard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.KPICard,
      })),
    { ssr: false },
  ),
  LabelDesigner: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.LabelDesigner,
      })),
    { ssr: false },
  ),
  LanguageSwitcher: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.LanguageSwitcher,
      })),
    { ssr: false },
  ),
  LeadPipelineBoard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.LeadPipelineBoard,
      })),
    { ssr: false },
  ),
  LeaveRequestForm: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.LeaveRequestForm,
      })),
    { ssr: false },
  ),
  LineChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.LineChart,
      })),
    { ssr: false },
  ),
  LineEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.LineEditor,
      })),
    { ssr: false },
  ),
  LoadingPage: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.LoadingPage,
      })),
    { ssr: false },
  ),
  MaintenanceLog: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MaintenanceLog,
      })),
    { ssr: false },
  ),
  MapChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MapChart,
      })),
    { ssr: false },
  ),
  MapMarker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MapMarkerCluster,
      })),
    { ssr: false },
  ),
  MapTrack: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MapTrack,
      })),
    { ssr: false },
  ),
  MapView: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MapView,
      })),
    { ssr: false },
  ),
  MarkdownEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MarkdownEditor,
      })),
    { ssr: false },
  ),
  MarketingActivityForm: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MarketingActivityForm,
      })),
    { ssr: false },
  ),
  MasterEditTemplate: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MasterEditTemplate,
      })),
    { ssr: false },
  ),
  MasterListTemplate: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MasterListTemplate,
      })),
    { ssr: false },
  ),
  MediaRecorder: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MediaRecorder,
      })),
    { ssr: false },
  ),
  MeetingRoomBooking: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MeetingRoomBooking,
      })),
    { ssr: false },
  ),
  MessageList: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MessageList,
      })),
    { ssr: false },
  ),
  MetricTrend: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MetricTrend,
      })),
    { ssr: false },
  ),
  MobileActionSheet: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MobileActionSheet,
      })),
    { ssr: false },
  ),
  MobileCamera: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MobileCamera,
      })),
    { ssr: false },
  ),
  MobileGeolocation: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MobileGeolocation,
      })),
    { ssr: false },
  ),
  MobileInfiniteScroll: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MobileInfiniteScroll,
      })),
    { ssr: false },
  ),
  MobileListItem: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MobileListItem,
      })),
    { ssr: false },
  ),
  MobilePageShell: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MobilePageShell,
      })),
    { ssr: false },
  ),
  MobilePicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MobilePicker,
      })),
    { ssr: false },
  ),
  MobileQrCodeScanner: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MobileQrCodeScanner,
      })),
    { ssr: false },
  ),
  MobileSignature: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MobileSignature,
      })),
    { ssr: false },
  ),
  MobileTabBar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MobileTabBar,
      })),
    { ssr: false },
  ),
  MultiCurrencyInput: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MultiCurrencyInput,
      })),
    { ssr: false },
  ),
  MultiSelect: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MultiSelect,
      })),
    { ssr: false },
  ),
  NotificationCenter: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.NotificationCenter,
      })),
    { ssr: false },
  ),
  NotificationRuleBuilder: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.NotificationRuleBuilder,
      })),
    { ssr: false },
  ),
  OaBridge: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.OaBridge,
      })),
    { ssr: false },
  ),
  OeeDashboard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.OeeDashboard,
      })),
    { ssr: false },
  ),
  OperationLog: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.OperationLog,
      })),
    { ssr: false },
  ),
  OrderLineEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.OrderLineEditor,
      })),
    { ssr: false },
  ),
  OrgChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.OrgChart,
      })),
    { ssr: false },
  ),
  OverviewPage: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.OverviewPage,
      })),
    { ssr: false },
  ),
  PageHeader: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PageHeader,
      })),
    { ssr: false },
  ),
  PasteUpload: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PasteUpload,
      })),
    { ssr: false },
  ),
  PaymentMethodSelector: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PaymentMethodSelector,
      })),
    { ssr: false },
  ),
  PaymentResult: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PaymentResult,
      })),
    { ssr: false },
  ),
  PaymentSchedule: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PaymentSchedule,
      })),
    { ssr: false },
  ),
  PdfViewer: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PDFViewer,
      })),
    { ssr: false },
  ),
  PerformanceRankTable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PerformanceRankTable,
      })),
    { ssr: false },
  ),
  PermissionButton: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PermissionButton,
      })),
    { ssr: false },
  ),
  PermissionMatrix: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PermissionMatrix,
      })),
    { ssr: false },
  ),
  PermissionWrapper: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PermissionWrapper,
      })),
    { ssr: false },
  ),
  PhotoAudit: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PhotoAudit,
      })),
    { ssr: false },
  ),
  PieChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PieChart,
      })),
    { ssr: false },
  ),
  PivotTable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PivotTable,
      })),
    { ssr: false },
  ),
  PolicyLineEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PolicyLineEditor,
      })),
    { ssr: false },
  ),
  PoolTrackerTable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PoolTrackerTable,
      })),
    { ssr: false },
  ),
  PreferencePanel: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PreferencePanel,
      })),
    { ssr: false },
  ),
  PriceAdjustBrowse: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PriceAdjustBrowse,
      })),
    { ssr: false },
  ),
  PrintButton: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PrintButton,
      })),
    { ssr: false },
  ),
  PrintService: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PrintService,
      })),
    { ssr: false },
  ),
  PrintTemplateBuilder: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PrintTemplateBuilder,
      })),
    { ssr: false },
  ),
  ProductBrowse: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ProductBrowse,
      })),
    { ssr: false },
  ),
  ProductCategoryPicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ProductCategoryPicker,
      })),
    { ssr: false },
  ),
  PromotionRuleCard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PromotionRuleCard,
      })),
    { ssr: false },
  ),
  PromotionRuleEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PromotionRuleEditor,
      })),
    { ssr: false },
  ),
  PromptDialog: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PromptDialog,
      })),
    { ssr: false },
  ),
  PurchaseOrderEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.PurchaseOrderEditor,
      })),
    { ssr: false },
  ),
  QualityInspectionForm: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.QualityInspectionForm,
      })),
    { ssr: false },
  ),
  QuickEntryGrid: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.QuickEntryGrid,
      })),
    { ssr: false },
  ),
  QuotationLineEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.QuotationLineEditor,
      })),
    { ssr: false },
  ),
  RadarChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.RadarChart,
      })),
    { ssr: false },
  ),
  RadialChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.RadialChart,
      })),
    { ssr: false },
  ),
  RebutNodeSelect: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.RebutNodeSelect,
      })),
    { ssr: false },
  ),
  ReconciliationLineEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ReconciliationLineEditor,
      })),
    { ssr: false },
  ),
  ReconciliationSummary: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ReconciliationSummary,
      })),
    { ssr: false },
  ),
  RedPacket: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.RedPacket,
      })),
    { ssr: false },
  ),
  RegionPicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.RegionPicker,
      })),
    { ssr: false },
  ),
  RemoteSelect: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.RemoteSelect,
      })),
    { ssr: false },
  ),
  ReportBuilder: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ReportBuilder,
      })),
    { ssr: false },
  ),
  ResourceSchedule: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ResourceSchedule,
      })),
    { ssr: false },
  ),
  ResponsivePreview: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ResponsivePreview,
      })),
    { ssr: false },
  ),
  RichTextEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.RichTextEditor,
      })),
    { ssr: false },
  ),
  RoleAssignment: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.RoleAssignment,
      })),
    { ssr: false },
  ),
  RuleEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.RuleEditor,
      })),
    { ssr: false },
  ),
  SalesOrderBrowse: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.SalesOrderBrowse,
      })),
    { ssr: false },
  ),
  SalesTargetEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.SalesTargetEditor,
      })),
    { ssr: false },
  ),
  SankeyChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.SankeyChart,
      })),
    { ssr: false },
  ),
  SavedFilters: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.SavedFilters,
      })),
    { ssr: false },
  ),
  ScatterChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ScatterChart,
      })),
    { ssr: false },
  ),
  SealStampRegistry: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.SealStampRegistry,
      })),
    { ssr: false },
  ),
  SearchTable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.SearchTable,
      })),
    { ssr: false },
  ),
  SerialNumberManager: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.SerialNumberManager,
      })),
    { ssr: false },
  ),
  SettlementStatusTag: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.SettlementStatusTag,
      })),
    { ssr: false },
  ),
  ShiftCalendar: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ShiftCalendar,
      })),
    { ssr: false },
  ),
  ShippingWayBrowse: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ShippingWayBrowse,
      })),
    { ssr: false },
  ),
  SignActionButton: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.SignActionButton,
      })),
    { ssr: false },
  ),
  SkuPicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.SkuPicker,
      })),
    { ssr: false },
  ),
  SocialShare: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.SocialShare,
      })),
    { ssr: false },
  ),
  SparkChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.SparkChart,
      })),
    { ssr: false },
  ),
  SpcControlChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.SPCControlChart,
      })),
    { ssr: false },
  ),
  SqlEditor: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.SqlEditor,
      })),
    { ssr: false },
  ),
  StatCardRow: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.StatCardRow,
      })),
    { ssr: false },
  ),
  StatCardWithDelta: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.StatCardWithDelta,
      })),
    { ssr: false },
  ),
  StatCardWithSparkline: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.StatCardWithSparkline,
      })),
    { ssr: false },
  ),
  StatCard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.StatCard,
      })),
    { ssr: false },
  ),
  StatusBadge: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.StatusBadge,
      })),
    { ssr: false },
  ),
  StatusTag: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.StatusTag,
      })),
    { ssr: false },
  ),
  StockTransferDialog: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.StockTransferDialog,
      })),
    { ssr: false },
  ),
  SubformTabs: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.SubformTabs,
      })),
    { ssr: false },
  ),
  SupplierScorecard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.SupplierScorecard,
      })),
    { ssr: false },
  ),
  TabCrudPage: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.TabCrudPage,
      })),
    { ssr: false },
  ),
  TabPin: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.TabPin,
      })),
    { ssr: false },
  ),
  TargetProgress: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.TargetProgress,
      })),
    { ssr: false },
  ),
  TaskHistory: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.TaskHistory,
      })),
    { ssr: false },
  ),
  TaskListTable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.TaskListTable,
      })),
    { ssr: false },
  ),
  TaskProgress: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.TaskProgress,
      })),
    { ssr: false },
  ),
  TaxDetailTable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.TaxDetailTable,
      })),
    { ssr: false },
  ),
  TemplateDownload: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.TemplateDownload,
      })),
    { ssr: false },
  ),
  TerritoryMap: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.TerritoryMap,
      })),
    { ssr: false },
  ),
  ThemeToggle: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ThemeToggle,
      })),
    { ssr: false },
  ),
  TimelineView: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.TimelineView,
      })),
    { ssr: false },
  ),
  TodoListTable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.TodoListTable,
      })),
    { ssr: false },
  ),
  Tracking: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.Tracking,
      })),
    { ssr: false },
  ),
  TreeCrudPage: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.TreeCrudPage,
      })),
    { ssr: false },
  ),
  TreeTable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.TreeTable,
      })),
    { ssr: false },
  ),
  TreemapChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.TreemapChart,
      })),
    { ssr: false },
  ),
  UnitConverter: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.UnitConverter,
      })),
    { ssr: false },
  ),
  UserMenu: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.UserMenu,
      })),
    { ssr: false },
  ),
  UtmBuilder: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.UtmBuilder,
      })),
    { ssr: false },
  ),
  VehicleBooking: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.VehicleBooking,
      })),
    { ssr: false },
  ),
  VersionHistory: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.VersionHistory,
      })),
    { ssr: false },
  ),
  WarehouseBrowse: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.WarehouseBrowse,
      })),
    { ssr: false },
  ),
  WarehousePicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.WarehousePicker,
      })),
    { ssr: false },
  ),
  WaterfallChart: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.WaterfallChart,
      })),
    { ssr: false },
  ),
  WorkOrderCard: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.WorkOrderCard,
      })),
    { ssr: false },
  ),
  WorkflowDesigner: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.WorkflowDesigner,
      })),
    { ssr: false },
  ),
  WorkflowPreview: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.WorkflowPreview,
      })),
    { ssr: false },
  ),
  WriteoffBrowse: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.WriteoffBrowse,
      })),
    { ssr: false },
  ),
  WriteoffFlow: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.WriteoffFlow,
      })),
    { ssr: false },
  ),
  PasswordInput: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.PasswordInput,
      })),
    { ssr: false },
  ),
  PhoneInput: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.PhoneInput,
      })),
    { ssr: false },
  ),
  MaskedInput: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.MaskedInput,
      })),
    { ssr: false },
  ),
  MonthPicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.MonthPicker,
      })),
    { ssr: false },
  ),
  YearPicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.YearPicker,
      })),
    { ssr: false },
  ),
  QuarterPicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.QuarterPicker,
      })),
    { ssr: false },
  ),
  RangeSlider: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.RangeSlider,
      })),
    { ssr: false },
  ),
  CountdownButton: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.CountdownButton,
      })),
    { ssr: false },
  ),
  AmountInput: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.AmountInput,
      })),
    { ssr: false },
  ),
  ProTable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ProTable,
      })),
    { ssr: false },
  ),
  SortableList: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.SortableList,
      })),
    { ssr: false },
  ),
  CopyButton: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.CopyButton,
      })),
    { ssr: false },
  ),
  LogViewer: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.LogViewer,
      })),
    { ssr: false },
  ),
  BarcodeScanner: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.BarcodeScanner,
      })),
    { ssr: false },
  ),
  ImageCropper: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ImageCropper,
      })),
    { ssr: false },
  ),
  EditableTable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.EditableTable,
      })),
    { ssr: false },
  ),
  EditableDescriptions: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.EditableDescriptions,
      })),
    { ssr: false },
  ),
  FilterChips: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.FilterChips,
      })),
    { ssr: false },
  ),
  SavedViewSwitcher: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.SavedViewSwitcher,
      })),
    { ssr: false },
  ),
  SkeletonTable: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.SkeletonTable,
      })),
    { ssr: false },
  ),
  SkeletonForm: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.SkeletonForm,
      })),
    { ssr: false },
  ),
  CodeDiffViewer: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.CodeDiffViewer,
      })),
    { ssr: false },
  ),
  MarkdownViewer: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.MarkdownViewer,
      })),
    { ssr: false },
  ),
  RichTextDisplay: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.RichTextDisplay,
      })),
    { ssr: false },
  ),
  LazyImage: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.LazyImage,
      })),
    { ssr: false },
  ),
  KeepAlive: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.KeepAlive,
      })),
    { ssr: false },
  ),
  MultiTabManager: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.MultiTabManager,
      })),
    { ssr: false },
  ),
  NotificationBadge: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.NotificationBadge,
      })),
    { ssr: false },
  ),
  NotificationDropdown: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.NotificationDropdown,
      })),
    { ssr: false },
  ),
  ErrorBoundaryUI: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.ErrorBoundaryUI,
      })),
    { ssr: false },
  ),
  I18nProvider: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.I18nProvider,
      })),
    { ssr: false },
  ),
  RTLProvider: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.RTLProvider,
      })),
    { ssr: false },
  ),
  KeyboardShortcutsManager: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.KeyboardShortcutsManager,
      })),
    { ssr: false },
  ),
  ImmersiveLayout: dynamic(
    () =>
      import("@chaos_team/chaos-ui/layout").then((m) => ({
        default: m.ImmersiveLayout,
      })),
    { ssr: false },
  ),
  OrgPicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.OrgPicker,
      })),
    { ssr: false },
  ),
  UserPicker: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.UserPicker,
      })),
    { ssr: false },
  ),
  AddressInput: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AddressInput,
      })),
    { ssr: false },
  ),
  JSONViewerUI: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.JSONViewerUI,
      })),
    { ssr: false },
  ),
  Heatmap: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.Heatmap,
      })),
    { ssr: false },
  ),
  SegmentedFilter: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.SegmentedFilter,
      })),
    { ssr: false },
  ),
  StatGrid: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.StatGrid,
      })),
    { ssr: false },
  ),
  RowContextMenu: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.RowContextMenu,
      })),
    { ssr: false },
  ),
  ProgressiveImage: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.ProgressiveImage,
      })),
    { ssr: false },
  ),
  PasswordPolicyValidator: dynamic(
    () =>
      import("@chaos_team/chaos-ui/ui").then((m) => ({
        default: m.PasswordPolicyValidator,
      })),
    { ssr: false },
  ),
  MarkdownViewerBiz: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.MarkdownViewerBiz,
      })),
    { ssr: false },
  ),
  AudioRecorder: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.AudioRecorder,
      })),
    { ssr: false },
  ),
  ScreenCapture: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.ScreenCapture,
      })),
    { ssr: false },
  ),
  OrgTreeSelect: dynamic(
    () =>
      import("@chaos_team/chaos-ui/business").then((m) => ({
        default: m.OrgTreeSelect,
      })),
    { ssr: false },
  ),
};

/**
 * Names of business components that require concrete data props to render.
 * The preview host uses this set to skip bare instantiation for names that
 * are NOT covered by a hand-authored fixture in `component-previews.tsx`.
 */
export const businessComponentNames: ReadonlySet<string> = new Set([
  "AccountBalance",
  "ActivityFeed",
  "AddressPicker",
  "AdvancedDataTable",
  "AdvancedSearch",
  "AnnouncementBanner",
  "AnnouncementCard",
  "ApplicationForm",
  "ApprovalActionBar",
  "ApprovalFlow",
  "ApprovalTimeline",
  "ArApAgingTable",
  "AreaChart",
  "AsyncTaskCenter",
  "AsyncTaskTrigger",
  "AttachmentList",
  "AttachmentPreview",
  "AttachmentUploader",
  "AttendanceCalendar",
  "AudienceSegmentBuilder",
  "AuditLog",
  "AuditSidebar",
  "AuditTrailDiff",
  "AuthGuard",
  "AvatarGroup",
  "BadgeDelta",
  "BarChart",
  "BarListCard",
  "BarList",
  "BatchGenealogyTree",
  "BatchPrintDialog",
  "BatchSelector",
  "BillFooter",
  "BillHeader",
  "BillPage",
  "BillPrintTemplate",
  "BillStatusBar",
  "BillTimeline",
  "BillTodoList",
  "BizStatusTag",
  "BomTreeEditor",
  "BrowseDialog",
  "BudgetAllocator",
  "BudgetOverview",
  "BudgetPacingCard",
  "BulkActionsToolbar",
  "BulkImportWizard",
  "CalendarView",
  "Callout",
  "CampaignCalendar",
  "CampaignCard",
  "CampaignStatusTag",
  "CategoryBar",
  "ChannelPicker",
  "ChartCard",
  "ChartSuite",
  "Chart",
  "ChatAgentStatus",
  "ChatArtifactPanel",
  "ChatBranch",
  "ChatCardMessage",
  "ChatCodeBlock",
  "ChatCommandMenu",
  "ChatContextPanel",
  "ChatConversationSearch",
  "ChatConversation",
  "ChatFeedback",
  "ChatHeader",
  "ChatImageGallery",
  "ChatInputToolbar",
  "ChatMarkdownRenderer",
  "ChatMentionPicker",
  "ChatMessageActions",
  "ChatMessageBubble",
  "ChatMessageGroup",
  "ChatMessageInput",
  "ChatModelSwitcher",
  "ChatSharedLink",
  "ChatShell",
  "ChatSidebar",
  "ChatStreamingText",
  "ChatSuggestReplies",
  "ChatThinkingBlock",
  "ChatToolCallBlock",
  "ChatVoiceMessage",
  "CheckoutBar",
  "Chip",
  "CityBrowse",
  "CodeBlock",
  "CodeEditor",
  "ColorBoard",
  "ColorTag",
  "CommandPalette",
  "CommissionCalculator",
  "CompanyBrowse",
  "CompanyPicker",
  "ComplianceChecklist",
  "ConfirmDialog",
  "ContractTemplate",
  "CookieBanner",
  "CostCenterPicker",
  "CouponCard",
  "CreativePreview",
  "CronEditor",
  "CrudPage",
  "CrudToolbar",
  "Customer360Card",
  "CustomerBrowse",
  "CustomerPicker",
  "DashboardCanvas",
  "DashboardDesigner",
  "DashboardGrid",
  "DataTable",
  "DateRangePicker",
  "DeltaBar",
  "DepartmentPicker",
  "DictSelect",
  "DiffViewerTable",
  "DiffViewer",
  "DistributorPicker",
  "DockPanel",
  "DonutCard",
  "DonutChart",
  "DynamicFormBuilder",
  "EditToolbar",
  "EditableTreeTable",
  "EmployeePicker",
  "EquipmentCard",
  "ErrorBoundary",
  "ErrorPage",
  "ExpenseLineEditor",
  "ExperimentSummary",
  "ExportButton",
  "FeatureTour",
  "FeeTypeBrowse",
  "FieldMask",
  "FileCard",
  "FileUploadManager",
  "FilterBar",
  "FilterBuilder",
  "FlowTracker",
  "Forbidden",
  "FormDesignerRuntime",
  "FormDesigner",
  "FormField",
  "FormWizard",
  "FormulaEditor",
  "FunnelChart",
  "GanttChartPro",
  "GanttChart",
  "GaugeChart",
  "Gauge",
  "GlobalLoading",
  "HeatmapCalendar",
  "HeatmapChart",
  "I18nFormField",
  "ImMessage",
  "ImageGallery",
  "ImportDialog",
  "ImportErrorTable",
  "ImportMappingWizard",
  "InlineEdit",
  "InventoryAlertList",
  "InventorySnapshot",
  "InviteLink",
  "InvoiceManager",
  "InvoiceSummary",
  "IotSensorGrid",
  "JournalEntryEditor",
  "JsonEditor",
  "JsonViewer",
  "KanbanBoard",
  "KanbanColumn",
  "KpiCard",
  "LabelDesigner",
  "LanguageSwitcher",
  "LeadPipelineBoard",
  "LeaveRequestForm",
  "LineChart",
  "LineEditor",
  "LoadingPage",
  "MaintenanceLog",
  "MapChart",
  "MapMarker",
  "MapTrack",
  "MapView",
  "MarkdownEditor",
  "MarketingActivityForm",
  "MasterEditTemplate",
  "MasterListTemplate",
  "MediaRecorder",
  "MeetingRoomBooking",
  "MessageList",
  "MetricTrend",
  "MobileActionSheet",
  "MobileCamera",
  "MobileGeolocation",
  "MobileInfiniteScroll",
  "MobileListItem",
  "MobilePageShell",
  "MobilePicker",
  "MobileQrCodeScanner",
  "MobileSignature",
  "MobileTabBar",
  "MultiCurrencyInput",
  "MultiSelect",
  "NotificationCenter",
  "NotificationRuleBuilder",
  "OaBridge",
  "OeeDashboard",
  "OperationLog",
  "OrderLineEditor",
  "OrgChart",
  "OverviewPage",
  "PageHeader",
  "PasteUpload",
  "PaymentMethodSelector",
  "PaymentResult",
  "PaymentSchedule",
  "PdfViewer",
  "PerformanceRankTable",
  "PermissionButton",
  "PermissionMatrix",
  "PermissionWrapper",
  "PhotoAudit",
  "PieChart",
  "PivotTable",
  "PolicyLineEditor",
  "PoolTrackerTable",
  "PreferencePanel",
  "PriceAdjustBrowse",
  "PrintButton",
  "PrintService",
  "PrintTemplateBuilder",
  "ProductBrowse",
  "ProductCategoryPicker",
  "PromotionRuleCard",
  "PromotionRuleEditor",
  "PromptDialog",
  "PurchaseOrderEditor",
  "QualityInspectionForm",
  "QuickEntryGrid",
  "QuotationLineEditor",
  "RadarChart",
  "RadialChart",
  "RebutNodeSelect",
  "ReconciliationLineEditor",
  "ReconciliationSummary",
  "RedPacket",
  "RegionPicker",
  "RemoteSelect",
  "ReportBuilder",
  "ResourceSchedule",
  "ResponsivePreview",
  "RichTextEditor",
  "RoleAssignment",
  "RuleEditor",
  "SalesOrderBrowse",
  "SalesTargetEditor",
  "SankeyChart",
  "SavedFilters",
  "ScatterChart",
  "SealStampRegistry",
  "SearchTable",
  "SerialNumberManager",
  "SettlementStatusTag",
  "ShiftCalendar",
  "ShippingWayBrowse",
  "SignActionButton",
  "SkuPicker",
  "SocialShare",
  "SparkChart",
  "SpcControlChart",
  "SqlEditor",
  "StatCardRow",
  "StatCardWithDelta",
  "StatCardWithSparkline",
  "StatCard",
  "StatusBadge",
  "StatusTag",
  "StockTransferDialog",
  "SubformTabs",
  "SupplierScorecard",
  "TabCrudPage",
  "TabPin",
  "TargetProgress",
  "TaskHistory",
  "TaskListTable",
  "TaskProgress",
  "TaxDetailTable",
  "TemplateDownload",
  "TerritoryMap",
  "ThemeToggle",
  "TimelineView",
  "TodoListTable",
  "Tracking",
  "TreeCrudPage",
  "TreeTable",
  "TreemapChart",
  "UnitConverter",
  "UserMenu",
  "UtmBuilder",
  "VehicleBooking",
  "VersionHistory",
  "WarehouseBrowse",
  "WarehousePicker",
  "WaterfallChart",
  "WorkOrderCard",
  "WorkflowDesigner",
  "WorkflowPreview",
  "WriteoffBrowse",
  "WriteoffFlow",
  "BarcodeScanner",
  "ImageCropper",
  "OrgPicker",
  "UserPicker",
  "MarkdownViewerBiz",
  "AudioRecorder",
  "ScreenCapture",
]);
