// AI-generated draft, manual review needed
//
// Source-of-truth: packages/chaos-design-ui/components/{ui,business,layout}/*.tsx
// The filesystem yields 192 real components; COMPONENT_INDEX.md lists 243, but ~120 of those
// have no source file yet (deferred to batch 2). This file only emits components whose
// sourcePath resolves to a real file — per Definition of Done for Agent B (02-meta-overview.md).

export type Category =
  | 'General'
  | 'Layout'
  | 'Navigation'
  | 'Form'
  | 'DataDisplay'
  | 'Feedback'
  | 'Business'
  | 'System Layout'

export interface ComponentMeta {
  /** kebab-case identifier used in the URL /components/[category]/[slug] */
  slug: string
  /** PascalCase component export name */
  name: string
  /** Chinese display name */
  nameZh: string
  /** One of the 8 product categories */
  category: Category
  /** one-sentence English description */
  desc: string
  /** one-sentence Chinese description */
  descZh: string
  /** optional icon name (lucide). Optional in batch 1. */
  icon?: string
  /** relative path to source file under packages/chaos-design-ui/ */
  sourcePath: string
  /** Storybook autodocs id, e.g. `components-button--docs`. Optional. */
  storybookId?: string
  /** free-form tags for search */
  tags?: string[]
}

export const CATEGORIES: Category[] = [
  'General',
  'Layout',
  'Navigation',
  'Form',
  'DataDisplay',
  'Feedback',
  'Business',
  'System Layout',
]

export const categoryLabelsZh: Record<Category, string> = {
  General: '通用',
  Layout: '布局',
  Navigation: '导航',
  Form: '表单',
  DataDisplay: '数据展示',
  Feedback: '反馈',
  Business: '业务',
  'System Layout': '系统布局',
}

export const categoryLabelsEn: Record<Category, string> = {
  'General': 'General',
  'Layout': 'Layout',
  'Navigation': 'Navigation',
  'Form': 'Form',
  'DataDisplay': 'DataDisplay',
  'Feedback': 'Feedback',
  'Business': 'Business',
  'System Layout': 'System Layout',
}

export const components: ComponentMeta[] = [
  {
    slug: 'accordion',
    name: "Accordion",
    nameZh: "折叠面板",
    category: 'General',
    desc: "Accordion — a primitive UI element for general use across the app.",
    descZh: "折叠面板 — 通用基础组件,适合在各种场景下复用。",
    sourcePath: 'packages/chaos-design-ui/components/ui/accordion.tsx',
    storybookId: 'components-accordion--docs',
  },
  {
    slug: 'browse-input',
    name: "BrowseInput",
    nameZh: "浏览输入",
    category: 'General',
    desc: "BrowseInput — a primitive UI element for general use across the app.",
    descZh: "浏览输入 — 通用基础组件,适合在各种场景下复用。",
    sourcePath: 'packages/chaos-design-ui/components/ui/browse-input.tsx',
    storybookId: 'components-browse-input--docs',
  },
  {
    slug: 'button',
    name: "Button",
    nameZh: "按钮",
    category: 'General',
    desc: "Button — a primitive UI element for general use across the app.",
    descZh: "按钮 — 通用基础组件,适合在各种场景下复用。",
    sourcePath: 'packages/chaos-design-ui/components/ui/button.tsx',
    storybookId: 'components-button--docs',
  },
  {
    slug: 'calendar',
    name: "Calendar",
    nameZh: "日历",
    category: 'General',
    desc: "Calendar — a primitive UI element for general use across the app.",
    descZh: "日历 — 通用基础组件,适合在各种场景下复用。",
    sourcePath: 'packages/chaos-design-ui/components/ui/calendar.tsx',
    storybookId: 'components-calendar--docs',
  },
  {
    slug: 'carousel',
    name: "Carousel",
    nameZh: "轮播",
    category: 'General',
    desc: "Carousel — a primitive UI element for general use across the app.",
    descZh: "轮播 — 通用基础组件,适合在各种场景下复用。",
    sourcePath: 'packages/chaos-design-ui/components/ui/carousel.tsx',
    storybookId: 'components-carousel--docs',
  },
  {
    slug: 'collapsible',
    name: "Collapsible",
    nameZh: "折叠",
    category: 'General',
    desc: "Collapsible — a primitive UI element for general use across the app.",
    descZh: "折叠 — 通用基础组件,适合在各种场景下复用。",
    sourcePath: 'packages/chaos-design-ui/components/ui/collapsible.tsx',
    storybookId: 'components-collapsible--docs',
  },
  {
    slug: 'context-menu',
    name: "ContextMenu",
    nameZh: "右键菜单",
    category: 'General',
    desc: "ContextMenu — a primitive UI element for general use across the app.",
    descZh: "右键菜单 — 通用基础组件,适合在各种场景下复用。",
    sourcePath: 'packages/chaos-design-ui/components/ui/context-menu.tsx',
    storybookId: 'components-context-menu--docs',
  },
  {
    slug: 'department-browse',
    name: "DepartmentBrowse",
    nameZh: "部门选择",
    category: 'General',
    desc: "DepartmentBrowse — a primitive UI element for general use across the app.",
    descZh: "部门选择 — 通用基础组件,适合在各种场景下复用。",
    sourcePath: 'packages/chaos-design-ui/components/ui/department-browse.tsx',
    storybookId: 'components-department-browse--docs',
  },
  {
    slug: 'dropdown-menu',
    name: "DropdownMenu",
    nameZh: "下拉菜单",
    category: 'General',
    desc: "DropdownMenu — a primitive UI element for general use across the app.",
    descZh: "下拉菜单 — 通用基础组件,适合在各种场景下复用。",
    sourcePath: 'packages/chaos-design-ui/components/ui/dropdown-menu.tsx',
    storybookId: 'components-dropdown-menu--docs',
  },
  {
    slug: 'user-browse',
    name: "UserBrowse",
    nameZh: "用户选择",
    category: 'General',
    desc: "UserBrowse — a primitive UI element for general use across the app.",
    descZh: "用户选择 — 通用基础组件,适合在各种场景下复用。",
    sourcePath: 'packages/chaos-design-ui/components/ui/user-browse.tsx',
    storybookId: 'components-user-browse--docs',
  },
  {
    slug: 'aspect-ratio',
    name: "AspectRatio",
    nameZh: "宽高比",
    category: 'Layout',
    desc: "AspectRatio — a layout utility for arranging page structure.",
    descZh: "宽高比 — 布局组件,用于组织页面结构。",
    sourcePath: 'packages/chaos-design-ui/components/ui/aspect-ratio.tsx',
    storybookId: 'components-aspect-ratio--docs',
  },
  {
    slug: 'grid-layout',
    name: "GridLayout",
    nameZh: "栅格布局",
    category: 'Layout',
    desc: "GridLayout — a layout utility for arranging page structure.",
    descZh: "栅格布局 — 布局组件,用于组织页面结构。",
    sourcePath: 'packages/chaos-design-ui/components/ui/grid-layout.tsx',
    storybookId: 'components-grid-layout--docs',
  },
  {
    slug: 'page-container',
    name: "PageContainer",
    nameZh: "页面容器",
    category: 'Layout',
    desc: "PageContainer — a layout utility for arranging page structure.",
    descZh: "页面容器 — 布局组件,用于组织页面结构。",
    sourcePath: 'packages/chaos-design-ui/components/ui/page-container.tsx',
    storybookId: 'components-page-container--docs',
  },
  {
    slug: 'resizable',
    name: "Resizable",
    nameZh: "可调尺寸",
    category: 'Layout',
    desc: "Resizable — a layout utility for arranging page structure.",
    descZh: "可调尺寸 — 布局组件,用于组织页面结构。",
    sourcePath: 'packages/chaos-design-ui/components/ui/resizable.tsx',
    storybookId: 'components-resizable--docs',
  },
  {
    slug: 'scroll-area',
    name: "ScrollArea",
    nameZh: "滚动区域",
    category: 'Layout',
    desc: "ScrollArea — a layout utility for arranging page structure.",
    descZh: "滚动区域 — 布局组件,用于组织页面结构。",
    sourcePath: 'packages/chaos-design-ui/components/ui/scroll-area.tsx',
    storybookId: 'components-scroll-area--docs',
  },
  {
    slug: 'separator',
    name: "Separator",
    nameZh: "分割线",
    category: 'Layout',
    desc: "Separator — a layout utility for arranging page structure.",
    descZh: "分割线 — 布局组件,用于组织页面结构。",
    sourcePath: 'packages/chaos-design-ui/components/ui/separator.tsx',
    storybookId: 'components-separator--docs',
  },
  {
    slug: 'split-pane',
    name: "SplitPane",
    nameZh: "分割面板",
    category: 'Layout',
    desc: "SplitPane — a layout utility for arranging page structure.",
    descZh: "分割面板 — 布局组件,用于组织页面结构。",
    sourcePath: 'packages/chaos-design-ui/components/ui/split-pane.tsx',
    storybookId: 'components-split-pane--docs',
  },
  {
    slug: 'breadcrumb',
    name: "Breadcrumb",
    nameZh: "面包屑",
    category: 'Navigation',
    desc: "Breadcrumb — a navigation element for moving between destinations.",
    descZh: "面包屑 — 导航组件,用于在页面或视图之间切换。",
    sourcePath: 'packages/chaos-design-ui/components/ui/breadcrumb.tsx',
    storybookId: 'components-breadcrumb--docs',
  },
  {
    slug: 'menubar',
    name: "Menubar",
    nameZh: "菜单栏",
    category: 'Navigation',
    desc: "Menubar — a navigation element for moving between destinations.",
    descZh: "菜单栏 — 导航组件,用于在页面或视图之间切换。",
    sourcePath: 'packages/chaos-design-ui/components/ui/menubar.tsx',
    storybookId: 'components-menubar--docs',
  },
  {
    slug: 'navigation-menu',
    name: "NavigationMenu",
    nameZh: "导航菜单",
    category: 'Navigation',
    desc: "NavigationMenu — a navigation element for moving between destinations.",
    descZh: "导航菜单 — 导航组件,用于在页面或视图之间切换。",
    sourcePath: 'packages/chaos-design-ui/components/ui/navigation-menu.tsx',
    storybookId: 'components-navigation-menu--docs',
  },
  {
    slug: 'pagination',
    name: "Pagination",
    nameZh: "分页",
    category: 'Navigation',
    desc: "Pagination — a navigation element for moving between destinations.",
    descZh: "分页 — 导航组件,用于在页面或视图之间切换。",
    sourcePath: 'packages/chaos-design-ui/components/ui/pagination.tsx',
    storybookId: 'components-pagination--docs',
  },
  {
    slug: 'sidebar',
    name: "Sidebar",
    nameZh: "侧边栏",
    category: 'Navigation',
    desc: "Sidebar — a navigation element for moving between destinations.",
    descZh: "侧边栏 — 导航组件,用于在页面或视图之间切换。",
    sourcePath: 'packages/chaos-design-ui/components/ui/sidebar.tsx',
    storybookId: 'components-sidebar--docs',
  },
  {
    slug: 'stepper',
    name: "Stepper",
    nameZh: "步骤条",
    category: 'Navigation',
    desc: "Stepper — a navigation element for moving between destinations.",
    descZh: "步骤条 — 导航组件,用于在页面或视图之间切换。",
    sourcePath: 'packages/chaos-design-ui/components/ui/stepper.tsx',
    storybookId: 'components-stepper--docs',
  },
  {
    slug: 'tabs',
    name: "Tabs",
    nameZh: "标签页",
    category: 'Navigation',
    desc: "Tabs — a navigation element for moving between destinations.",
    descZh: "标签页 — 导航组件,用于在页面或视图之间切换。",
    sourcePath: 'packages/chaos-design-ui/components/ui/tabs.tsx',
    storybookId: 'components-tabs--docs',
  },
  {
    slug: 'checkbox',
    name: "Checkbox",
    nameZh: "复选框",
    category: 'Form',
    desc: "Checkbox — a form control for capturing structured user input.",
    descZh: "复选框 — 表单控件,用于采集结构化的用户输入。",
    sourcePath: 'packages/chaos-design-ui/components/ui/checkbox.tsx',
    storybookId: 'components-checkbox--docs',
  },
  {
    slug: 'color-picker',
    name: "ColorPicker",
    nameZh: "颜色选择器",
    category: 'Form',
    desc: "ColorPicker — a form control for capturing structured user input.",
    descZh: "颜色选择器 — 表单控件,用于采集结构化的用户输入。",
    sourcePath: 'packages/chaos-design-ui/components/ui/color-picker.tsx',
    storybookId: 'components-color-picker--docs',
  },
  {
    slug: 'file-upload',
    name: "FileUpload",
    nameZh: "文件上传",
    category: 'Form',
    desc: "FileUpload — a form control for capturing structured user input.",
    descZh: "文件上传 — 表单控件,用于采集结构化的用户输入。",
    sourcePath: 'packages/chaos-design-ui/components/ui/file-upload.tsx',
    storybookId: 'components-file-upload--docs',
  },
  {
    slug: 'form-grid',
    name: "FormGrid",
    nameZh: "表单栅格",
    category: 'Form',
    desc: "FormGrid — a form control for capturing structured user input.",
    descZh: "表单栅格 — 表单控件,用于采集结构化的用户输入。",
    sourcePath: 'packages/chaos-design-ui/components/ui/form-grid.tsx',
    storybookId: 'components-form-grid--docs',
  },
  {
    slug: 'form-list',
    name: "FormList",
    nameZh: "表单列表",
    category: 'Form',
    desc: "FormList — a form control for capturing structured user input.",
    descZh: "表单列表 — 表单控件,用于采集结构化的用户输入。",
    sourcePath: 'packages/chaos-design-ui/components/ui/form-list.tsx',
    storybookId: 'components-form-list--docs',
  },
  {
    slug: 'form-section',
    name: "FormSection",
    nameZh: "表单分组",
    category: 'Form',
    desc: "FormSection — a form control for capturing structured user input.",
    descZh: "表单分组 — 表单控件,用于采集结构化的用户输入。",
    sourcePath: 'packages/chaos-design-ui/components/ui/form-section.tsx',
    storybookId: 'components-form-section--docs',
  },
  {
    slug: 'input',
    name: "Input",
    nameZh: "输入框",
    category: 'Form',
    desc: "Input — a form control for capturing structured user input.",
    descZh: "输入框 — 表单控件,用于采集结构化的用户输入。",
    sourcePath: 'packages/chaos-design-ui/components/ui/input.tsx',
    storybookId: 'components-input--docs',
  },
  {
    slug: 'input-group',
    name: "InputGroup",
    nameZh: "输入组",
    category: 'Form',
    desc: "InputGroup — a form control for capturing structured user input.",
    descZh: "输入组 — 表单控件,用于采集结构化的用户输入。",
    sourcePath: 'packages/chaos-design-ui/components/ui/input-group.tsx',
    storybookId: 'components-input-group--docs',
  },
  {
    slug: 'otp-field',
    name: "OtpField",
    nameZh: "OTP 输入",
    category: 'Form',
    desc: "OtpField — a form control for capturing structured user input.",
    descZh: "OTP 输入 — 表单控件,用于采集结构化的用户输入。",
    sourcePath: 'packages/chaos-design-ui/components/ui/otp-field.tsx',
    storybookId: 'components-otp-field--docs',
  },
  {
    slug: 'radio-group',
    name: "RadioGroup",
    nameZh: "单选组",
    category: 'Form',
    desc: "RadioGroup — a form control for capturing structured user input.",
    descZh: "单选组 — 表单控件,用于采集结构化的用户输入。",
    sourcePath: 'packages/chaos-design-ui/components/ui/radio-group.tsx',
    storybookId: 'components-radio-group--docs',
  },
  {
    slug: 'select',
    name: "Select",
    nameZh: "选择器",
    category: 'Form',
    desc: "Select — a form control for capturing structured user input.",
    descZh: "选择器 — 表单控件,用于采集结构化的用户输入。",
    sourcePath: 'packages/chaos-design-ui/components/ui/select.tsx',
    storybookId: 'components-select--docs',
  },
  {
    slug: 'slider',
    name: "Slider",
    nameZh: "滑块",
    category: 'Form',
    desc: "Slider — a form control for capturing structured user input.",
    descZh: "滑块 — 表单控件,用于采集结构化的用户输入。",
    sourcePath: 'packages/chaos-design-ui/components/ui/slider.tsx',
    storybookId: 'components-slider--docs',
  },
  {
    slug: 'switch',
    name: "Switch",
    nameZh: "开关",
    category: 'Form',
    desc: "Switch — a form control for capturing structured user input.",
    descZh: "开关 — 表单控件,用于采集结构化的用户输入。",
    sourcePath: 'packages/chaos-design-ui/components/ui/switch.tsx',
    storybookId: 'components-switch--docs',
  },
  {
    slug: 'tags-input',
    name: "TagsInput",
    nameZh: "标签输入",
    category: 'Form',
    desc: "TagsInput — a form control for capturing structured user input.",
    descZh: "标签输入 — 表单控件,用于采集结构化的用户输入。",
    sourcePath: 'packages/chaos-design-ui/components/ui/tags-input.tsx',
    storybookId: 'components-tags-input--docs',
  },
  {
    slug: 'textarea',
    name: "Textarea",
    nameZh: "文本域",
    category: 'Form',
    desc: "Textarea — a form control for capturing structured user input.",
    descZh: "文本域 — 表单控件,用于采集结构化的用户输入。",
    sourcePath: 'packages/chaos-design-ui/components/ui/textarea.tsx',
    storybookId: 'components-textarea--docs',
  },
  {
    slug: 'toggle',
    name: "Toggle",
    nameZh: "开关",
    category: 'Form',
    desc: "Toggle — a form control for capturing structured user input.",
    descZh: "开关 — 表单控件,用于采集结构化的用户输入。",
    sourcePath: 'packages/chaos-design-ui/components/ui/toggle.tsx',
    storybookId: 'components-toggle--docs',
  },
  {
    slug: 'toggle-group',
    name: "ToggleGroup",
    nameZh: "按钮组",
    category: 'Form',
    desc: "ToggleGroup — a form control for capturing structured user input.",
    descZh: "按钮组 — 表单控件,用于采集结构化的用户输入。",
    sourcePath: 'packages/chaos-design-ui/components/ui/toggle-group.tsx',
    storybookId: 'components-toggle-group--docs',
  },
  {
    slug: 'tree-select',
    name: "TreeSelect",
    nameZh: "树选择",
    category: 'Form',
    desc: "TreeSelect — a form control for capturing structured user input.",
    descZh: "树选择 — 表单控件,用于采集结构化的用户输入。",
    sourcePath: 'packages/chaos-design-ui/components/ui/tree-select.tsx',
    storybookId: 'components-tree-select--docs',
  },
  {
    slug: 'avatar',
    name: "Avatar",
    nameZh: "头像",
    category: 'DataDisplay',
    desc: "Avatar — a data display widget for presenting structured information.",
    descZh: "头像 — 数据展示组件,用于呈现结构化信息。",
    sourcePath: 'packages/chaos-design-ui/components/ui/avatar.tsx',
    storybookId: 'components-avatar--docs',
  },
  {
    slug: 'badge',
    name: "Badge",
    nameZh: "徽标",
    category: 'DataDisplay',
    desc: "Badge — a data display widget for presenting structured information.",
    descZh: "徽标 — 数据展示组件,用于呈现结构化信息。",
    sourcePath: 'packages/chaos-design-ui/components/ui/badge.tsx',
    storybookId: 'components-badge--docs',
  },
  {
    slug: 'card',
    name: "Card",
    nameZh: "卡片",
    category: 'DataDisplay',
    desc: "Card — a data display widget for presenting structured information.",
    descZh: "卡片 — 数据展示组件,用于呈现结构化信息。",
    sourcePath: 'packages/chaos-design-ui/components/ui/card.tsx',
    storybookId: 'components-card--docs',
  },
  {
    slug: 'dot',
    name: "Dot",
    nameZh: "小圆点",
    category: 'DataDisplay',
    desc: "Dot — a data display widget for presenting structured information.",
    descZh: "小圆点 — 数据展示组件,用于呈现结构化信息。",
    sourcePath: 'packages/chaos-design-ui/components/ui/dot.tsx',
    storybookId: 'components-dot--docs',
  },
  {
    slug: 'kbd',
    name: "Kbd",
    nameZh: "键盘按键",
    category: 'DataDisplay',
    desc: "Kbd — a data display widget for presenting structured information.",
    descZh: "键盘按键 — 数据展示组件,用于呈现结构化信息。",
    sourcePath: 'packages/chaos-design-ui/components/ui/kbd.tsx',
    storybookId: 'components-kbd--docs',
  },
  {
    slug: 'kpi-panel',
    name: "KpiPanel",
    nameZh: "KPI 面板",
    category: 'DataDisplay',
    desc: "KpiPanel — a data display widget for presenting structured information.",
    descZh: "KPI 面板 — 数据展示组件,用于呈现结构化信息。",
    sourcePath: 'packages/chaos-design-ui/components/ui/kpi-panel.tsx',
    storybookId: 'components-kpi-panel--docs',
  },
  {
    slug: 'label',
    name: "Label",
    nameZh: "标签",
    category: 'DataDisplay',
    desc: "Label — a data display widget for presenting structured information.",
    descZh: "标签 — 数据展示组件,用于呈现结构化信息。",
    sourcePath: 'packages/chaos-design-ui/components/ui/label.tsx',
    storybookId: 'components-label--docs',
  },
  {
    slug: 'table',
    name: "Table",
    nameZh: "表格",
    category: 'DataDisplay',
    desc: "Table — a data display widget for presenting structured information.",
    descZh: "表格 — 数据展示组件,用于呈现结构化信息。",
    sourcePath: 'packages/chaos-design-ui/components/ui/table.tsx',
    storybookId: 'components-table--docs',
  },
  {
    slug: 'timeline',
    name: "Timeline",
    nameZh: "时间线",
    category: 'DataDisplay',
    desc: "Timeline — a data display widget for presenting structured information.",
    descZh: "时间线 — 数据展示组件,用于呈现结构化信息。",
    sourcePath: 'packages/chaos-design-ui/components/ui/timeline.tsx',
    storybookId: 'components-timeline--docs',
  },
  {
    slug: 'tree-view',
    name: "TreeView",
    nameZh: "树视图",
    category: 'DataDisplay',
    desc: "TreeView — a data display widget for presenting structured information.",
    descZh: "树视图 — 数据展示组件,用于呈现结构化信息。",
    sourcePath: 'packages/chaos-design-ui/components/ui/tree-view.tsx',
    storybookId: 'components-tree-view--docs',
  },
  {
    slug: 'virtual-list',
    name: "VirtualList",
    nameZh: "虚拟列表",
    category: 'DataDisplay',
    desc: "VirtualList — a data display widget for presenting structured information.",
    descZh: "虚拟列表 — 数据展示组件,用于呈现结构化信息。",
    sourcePath: 'packages/chaos-design-ui/components/ui/virtual-list.tsx',
    storybookId: 'components-virtual-list--docs',
  },
  {
    slug: 'virtual-table',
    name: "VirtualTable",
    nameZh: "虚拟表格",
    category: 'DataDisplay',
    desc: "VirtualTable — a data display widget for presenting structured information.",
    descZh: "虚拟表格 — 数据展示组件,用于呈现结构化信息。",
    sourcePath: 'packages/chaos-design-ui/components/ui/virtual-table.tsx',
    storybookId: 'components-virtual-table--docs',
  },
  {
    slug: 'alert',
    name: "Alert",
    nameZh: "警告提示",
    category: 'Feedback',
    desc: "Alert — a feedback overlay for transient user notifications.",
    descZh: "警告提示 — 反馈层组件,用于瞬态用户通知或确认。",
    sourcePath: 'packages/chaos-design-ui/components/ui/alert.tsx',
    storybookId: 'components-alert--docs',
  },
  {
    slug: 'alert-dialog',
    name: "AlertDialog",
    nameZh: "警告对话框",
    category: 'Feedback',
    desc: "AlertDialog — a feedback overlay for transient user notifications.",
    descZh: "警告对话框 — 反馈层组件,用于瞬态用户通知或确认。",
    sourcePath: 'packages/chaos-design-ui/components/ui/alert-dialog.tsx',
    storybookId: 'components-alert-dialog--docs',
  },
  {
    slug: 'command',
    name: "Command",
    nameZh: "命令面板",
    category: 'Feedback',
    desc: "Command — a feedback overlay for transient user notifications.",
    descZh: "命令面板 — 反馈层组件,用于瞬态用户通知或确认。",
    sourcePath: 'packages/chaos-design-ui/components/ui/command.tsx',
    storybookId: 'components-command--docs',
  },
  {
    slug: 'dialog',
    name: "Dialog",
    nameZh: "对话框",
    category: 'Feedback',
    desc: "Dialog — a feedback overlay for transient user notifications.",
    descZh: "对话框 — 反馈层组件,用于瞬态用户通知或确认。",
    sourcePath: 'packages/chaos-design-ui/components/ui/dialog.tsx',
    storybookId: 'components-dialog--docs',
  },
  {
    slug: 'drawer',
    name: "Drawer",
    nameZh: "抽屉",
    category: 'Feedback',
    desc: "Drawer — a feedback overlay for transient user notifications.",
    descZh: "抽屉 — 反馈层组件,用于瞬态用户通知或确认。",
    sourcePath: 'packages/chaos-design-ui/components/ui/drawer.tsx',
    storybookId: 'components-drawer--docs',
  },
  {
    slug: 'hover-card',
    name: "HoverCard",
    nameZh: "悬停卡片",
    category: 'Feedback',
    desc: "HoverCard — a feedback overlay for transient user notifications.",
    descZh: "悬停卡片 — 反馈层组件,用于瞬态用户通知或确认。",
    sourcePath: 'packages/chaos-design-ui/components/ui/hover-card.tsx',
    storybookId: 'components-hover-card--docs',
  },
  {
    slug: 'popover',
    name: "Popover",
    nameZh: "气泡卡片",
    category: 'Feedback',
    desc: "Popover — a feedback overlay for transient user notifications.",
    descZh: "气泡卡片 — 反馈层组件,用于瞬态用户通知或确认。",
    sourcePath: 'packages/chaos-design-ui/components/ui/popover.tsx',
    storybookId: 'components-popover--docs',
  },
  {
    slug: 'progress',
    name: "Progress",
    nameZh: "进度条",
    category: 'Feedback',
    desc: "Progress — a feedback overlay for transient user notifications.",
    descZh: "进度条 — 反馈层组件,用于瞬态用户通知或确认。",
    sourcePath: 'packages/chaos-design-ui/components/ui/progress.tsx',
    storybookId: 'components-progress--docs',
  },
  {
    slug: 'sheet',
    name: "Sheet",
    nameZh: "抽屉",
    category: 'Feedback',
    desc: "Sheet — a feedback overlay for transient user notifications.",
    descZh: "抽屉 — 反馈层组件,用于瞬态用户通知或确认。",
    sourcePath: 'packages/chaos-design-ui/components/ui/sheet.tsx',
    storybookId: 'components-sheet--docs',
  },
  {
    slug: 'skeleton',
    name: "Skeleton",
    nameZh: "骨架屏",
    category: 'Feedback',
    desc: "Skeleton — a feedback overlay for transient user notifications.",
    descZh: "骨架屏 — 反馈层组件,用于瞬态用户通知或确认。",
    sourcePath: 'packages/chaos-design-ui/components/ui/skeleton.tsx',
    storybookId: 'components-skeleton--docs',
  },
  {
    slug: 'sonner',
    name: "Sonner",
    nameZh: "消息提示",
    category: 'Feedback',
    desc: "Sonner — a feedback overlay for transient user notifications.",
    descZh: "消息提示 — 反馈层组件,用于瞬态用户通知或确认。",
    sourcePath: 'packages/chaos-design-ui/components/ui/sonner.tsx',
    storybookId: 'components-sonner--docs',
  },
  {
    slug: 'tooltip',
    name: "Tooltip",
    nameZh: "文字提示",
    category: 'Feedback',
    desc: "Tooltip — a feedback overlay for transient user notifications.",
    descZh: "文字提示 — 反馈层组件,用于瞬态用户通知或确认。",
    sourcePath: 'packages/chaos-design-ui/components/ui/tooltip.tsx',
    storybookId: 'components-tooltip--docs',
  },
  {
    slug: 'activity-feed',
    name: "ActivityFeed",
    nameZh: "动态流",
    category: 'Business',
    desc: "ActivityFeed — a business component tailored to ERP/marketing scenarios.",
    descZh: "动态流 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/activity-feed.tsx',
    storybookId: 'components-activity-feed--docs',
  },
  {
    slug: 'address-form',
    name: "AddressForm",
    nameZh: "地址表单",
    category: 'Business',
    desc: "AddressForm — a business component tailored to ERP/marketing scenarios.",
    descZh: "地址表单 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/address-form.tsx',
    storybookId: 'components-address-form--docs',
  },
  {
    slug: 'advanced-data-table',
    name: "AdvancedDataTable",
    nameZh: "增强数据表",
    category: 'Business',
    desc: "AdvancedDataTable — a business component tailored to ERP/marketing scenarios.",
    descZh: "增强数据表 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/advanced-data-table.tsx',
    storybookId: 'components-advanced-data-table--docs',
  },
  {
    slug: 'anchor',
    name: "Anchor",
    nameZh: "锚点",
    category: 'Business',
    desc: "Anchor — a business component tailored to ERP/marketing scenarios.",
    descZh: "锚点 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/anchor.tsx',
    storybookId: 'components-anchor--docs',
  },
  {
    slug: 'animated-number',
    name: "AnimatedNumber",
    nameZh: "数字动画",
    category: 'Business',
    desc: "AnimatedNumber — a business component tailored to ERP/marketing scenarios.",
    descZh: "AnimatedNumber — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/animated-number.tsx',
    storybookId: 'components-animated-number--docs',
  },
  {
    slug: 'approval-flow',
    name: "ApprovalFlow",
    nameZh: "审批流程",
    category: 'Business',
    desc: "ApprovalFlow — a business component tailored to ERP/marketing scenarios.",
    descZh: "ApprovalFlow — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/approval-flow.tsx',
    storybookId: 'components-approval-flow--docs',
  },
  {
    slug: 'audio-player',
    name: "AudioPlayer",
    nameZh: "音频播放器",
    category: 'Business',
    desc: "AudioPlayer — a business component tailored to ERP/marketing scenarios.",
    descZh: "AudioPlayer — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/audio-player.tsx',
    storybookId: 'components-audio-player--docs',
  },
  {
    slug: 'audit-log',
    name: "AuditLog",
    nameZh: "审计日志",
    category: 'Business',
    desc: "AuditLog — a business component tailored to ERP/marketing scenarios.",
    descZh: "审计日志 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/audit-log.tsx',
    storybookId: 'components-audit-log--docs',
  },
  {
    slug: 'auth-forms',
    name: "AuthForms",
    nameZh: "认证表单",
    category: 'Business',
    desc: "AuthForms — a business component tailored to ERP/marketing scenarios.",
    descZh: "认证表单 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/auth-forms.tsx',
    storybookId: 'components-auth-forms--docs',
  },
  {
    slug: 'avatar-group',
    name: "AvatarGroup",
    nameZh: "头像组",
    category: 'Business',
    desc: "AvatarGroup — a business component tailored to ERP/marketing scenarios.",
    descZh: "头像组 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/avatar-group.tsx',
    storybookId: 'components-avatar-group--docs',
  },
  {
    slug: 'banner',
    name: "Banner",
    nameZh: "横幅",
    category: 'Business',
    desc: "Banner — a business component tailored to ERP/marketing scenarios.",
    descZh: "Banner — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/banner.tsx',
    storybookId: 'components-banner--docs',
  },
  {
    slug: 'barcode-display',
    name: "BarcodeDisplay",
    nameZh: "条形码显示",
    category: 'Business',
    desc: "BarcodeDisplay — a business component tailored to ERP/marketing scenarios.",
    descZh: "BarcodeDisplay — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/barcode-display.tsx',
    storybookId: 'components-barcode-display--docs',
  },
  {
    slug: 'bulk-actions-toolbar',
    name: "BulkActionsToolbar",
    nameZh: "批量操作工具栏",
    category: 'Business',
    desc: "BulkActionsToolbar — a business component tailored to ERP/marketing scenarios.",
    descZh: "批量操作工具栏 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/bulk-actions-toolbar.tsx',
    storybookId: 'components-bulk-actions-toolbar--docs',
  },
  {
    slug: 'chart',
    name: "Chart",
    nameZh: "图表",
    category: 'Business',
    desc: "Chart — a business component tailored to ERP/marketing scenarios.",
    descZh: "图表 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/chart.tsx',
    storybookId: 'components-chart--docs',
  },
  {
    slug: 'chat',
    name: "Chat",
    nameZh: "聊天",
    category: 'Business',
    desc: "Chat — a business component tailored to ERP/marketing scenarios.",
    descZh: "Chat — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/chat.tsx',
    storybookId: 'components-chat--docs',
  },
  {
    slug: 'chip',
    name: "Chip",
    nameZh: "标签块",
    category: 'Business',
    desc: "Chip — a business component tailored to ERP/marketing scenarios.",
    descZh: "标签块 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/chip.tsx',
    storybookId: 'components-chip--docs',
  },
  {
    slug: 'coach-mark',
    name: "CoachMark",
    nameZh: "引导标记",
    category: 'Business',
    desc: "CoachMark — a business component tailored to ERP/marketing scenarios.",
    descZh: "CoachMark — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/coach-mark.tsx',
    storybookId: 'components-coach-mark--docs',
  },
  {
    slug: 'code-block',
    name: "CodeBlock",
    nameZh: "代码块",
    category: 'Business',
    desc: "CodeBlock — a business component tailored to ERP/marketing scenarios.",
    descZh: "代码块 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/code-block.tsx',
    storybookId: 'components-code-block--docs',
  },
  {
    slug: 'code-editor',
    name: "CodeEditor",
    nameZh: "代码编辑器",
    category: 'Business',
    desc: "CodeEditor — a business component tailored to ERP/marketing scenarios.",
    descZh: "CodeEditor — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/code-editor.tsx',
    storybookId: 'components-code-editor--docs',
  },
  {
    slug: 'combobox',
    name: "Combobox",
    nameZh: "组合选择",
    category: 'Business',
    desc: "Combobox — a business component tailored to ERP/marketing scenarios.",
    descZh: "组合选择 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/combobox.tsx',
    storybookId: 'components-combobox--docs',
  },
  {
    slug: 'command-palette',
    name: "CommandPalette",
    nameZh: "命令面板",
    category: 'Business',
    desc: "CommandPalette — a business component tailored to ERP/marketing scenarios.",
    descZh: "命令面板 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/command-palette.tsx',
    storybookId: 'components-command-palette--docs',
  },
  {
    slug: 'comment-thread',
    name: "CommentThread",
    nameZh: "评论线程",
    category: 'Business',
    desc: "CommentThread — a business component tailored to ERP/marketing scenarios.",
    descZh: "CommentThread — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/comment-thread.tsx',
    storybookId: 'components-comment-thread--docs',
  },
  {
    slug: 'confetti',
    name: "Confetti",
    nameZh: "庆祝动画",
    category: 'Business',
    desc: "Confetti — a business component tailored to ERP/marketing scenarios.",
    descZh: "Confetti — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/confetti.tsx',
    storybookId: 'components-confetti--docs',
  },
  {
    slug: 'confirm-dialog',
    name: "ConfirmDialog",
    nameZh: "确认对话框",
    category: 'Business',
    desc: "ConfirmDialog — a business component tailored to ERP/marketing scenarios.",
    descZh: "确认对话框 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/confirm-dialog.tsx',
    storybookId: 'components-confirm-dialog--docs',
  },
  {
    slug: 'connection-status',
    name: "ConnectionStatus",
    nameZh: "连接状态",
    category: 'Business',
    desc: "ConnectionStatus — a business component tailored to ERP/marketing scenarios.",
    descZh: "ConnectionStatus — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/connection-status.tsx',
    storybookId: 'components-connection-status--docs',
  },
  {
    slug: 'cookie-banner',
    name: "CookieBanner",
    nameZh: "Cookie 横幅",
    category: 'Business',
    desc: "CookieBanner — a business component tailored to ERP/marketing scenarios.",
    descZh: "Cookie 横幅 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/cookie-banner.tsx',
    storybookId: 'components-cookie-banner--docs',
  },
  {
    slug: 'copy-button',
    name: "CopyButton",
    nameZh: "复制按钮",
    category: 'Business',
    desc: "CopyButton — a business component tailored to ERP/marketing scenarios.",
    descZh: "CopyButton — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/copy-button.tsx',
    storybookId: 'components-copy-button--docs',
  },
  {
    slug: 'credit-card-input',
    name: "CreditCardInput",
    nameZh: "信用卡输入",
    category: 'Business',
    desc: "CreditCardInput — a business component tailored to ERP/marketing scenarios.",
    descZh: "CreditCardInput — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/credit-card-input.tsx',
    storybookId: 'components-credit-card-input--docs',
  },
  {
    slug: 'currency-input',
    name: "CurrencyInput",
    nameZh: "货币输入",
    category: 'Business',
    desc: "CurrencyInput — a business component tailored to ERP/marketing scenarios.",
    descZh: "CurrencyInput — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/currency-input.tsx',
    storybookId: 'components-currency-input--docs',
  },
  {
    slug: 'data-table',
    name: "DataTable",
    nameZh: "数据表",
    category: 'Business',
    desc: "DataTable — a business component tailored to ERP/marketing scenarios.",
    descZh: "数据表 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/data-table.tsx',
    storybookId: 'components-data-table--docs',
  },
  {
    slug: 'date-range-picker',
    name: "DateRangePicker",
    nameZh: "日期范围选择器",
    category: 'Business',
    desc: "DateRangePicker — a business component tailored to ERP/marketing scenarios.",
    descZh: "日期范围选择器 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/date-range-picker.tsx',
    storybookId: 'components-date-range-picker--docs',
  },
  {
    slug: 'density-switcher',
    name: "DensitySwitcher",
    nameZh: "密度切换",
    category: 'Business',
    desc: "DensitySwitcher — a business component tailored to ERP/marketing scenarios.",
    descZh: "DensitySwitcher — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/density-switcher.tsx',
    storybookId: 'components-density-switcher--docs',
  },
  {
    slug: 'dock',
    name: "Dock",
    nameZh: "停靠栏",
    category: 'Business',
    desc: "Dock — a business component tailored to ERP/marketing scenarios.",
    descZh: "Dock — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/dock.tsx',
    storybookId: 'components-dock--docs',
  },
  {
    slug: 'empty-state',
    name: "EmptyState",
    nameZh: "空状态",
    category: 'Business',
    desc: "EmptyState — a business component tailored to ERP/marketing scenarios.",
    descZh: "空状态 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/empty-state.tsx',
    storybookId: 'components-empty-state--docs',
  },
  {
    slug: 'error-boundary',
    name: "ErrorBoundary",
    nameZh: "错误边界",
    category: 'Business',
    desc: "ErrorBoundary — a business component tailored to ERP/marketing scenarios.",
    descZh: "错误边界 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/error-boundary.tsx',
    storybookId: 'components-error-boundary--docs',
  },
  {
    slug: 'error-page',
    name: "ErrorPage",
    nameZh: "错误页",
    category: 'Business',
    desc: "ErrorPage — a business component tailored to ERP/marketing scenarios.",
    descZh: "错误页 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/error-page.tsx',
    storybookId: 'components-error-page--docs',
  },
  {
    slug: 'export-button',
    name: "ExportButton",
    nameZh: "导出按钮",
    category: 'Business',
    desc: "ExportButton — a business component tailored to ERP/marketing scenarios.",
    descZh: "导出按钮 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/export-button.tsx',
    storybookId: 'components-export-button--docs',
  },
  {
    slug: 'fab',
    name: "Fab",
    nameZh: "悬浮按钮",
    category: 'Business',
    desc: "Fab — a business component tailored to ERP/marketing scenarios.",
    descZh: "悬浮按钮 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/fab.tsx',
    storybookId: 'components-fab--docs',
  },
  {
    slug: 'feature-gate',
    name: "FeatureGate",
    nameZh: "功能开关",
    category: 'Business',
    desc: "FeatureGate — a business component tailored to ERP/marketing scenarios.",
    descZh: "FeatureGate — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/feature-gate.tsx',
    storybookId: 'components-feature-gate--docs',
  },
  {
    slug: 'file-upload-manager',
    name: "FileUploadManager",
    nameZh: "上传管理",
    category: 'Business',
    desc: "FileUploadManager — a business component tailored to ERP/marketing scenarios.",
    descZh: "上传管理 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/file-upload-manager.tsx',
    storybookId: 'components-file-upload-manager--docs',
  },
  {
    slug: 'filter-builder',
    name: "FilterBuilder",
    nameZh: "条件构建器",
    category: 'Business',
    desc: "FilterBuilder — a business component tailored to ERP/marketing scenarios.",
    descZh: "条件构建器 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/filter-builder.tsx',
    storybookId: 'components-filter-builder--docs',
  },
  {
    slug: 'form-field',
    name: "FormField",
    nameZh: "表单字段",
    category: 'Business',
    desc: "FormField — a business component tailored to ERP/marketing scenarios.",
    descZh: "表单字段 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/form-field.tsx',
    storybookId: 'components-form-field--docs',
  },
  {
    slug: 'form-wizard',
    name: "FormWizard",
    nameZh: "表单向导",
    category: 'Business',
    desc: "FormWizard — a business component tailored to ERP/marketing scenarios.",
    descZh: "表单向导 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/form-wizard.tsx',
    storybookId: 'components-form-wizard--docs',
  },
  {
    slug: 'gauge',
    name: "Gauge",
    nameZh: "仪表盘",
    category: 'Business',
    desc: "Gauge — a business component tailored to ERP/marketing scenarios.",
    descZh: "仪表盘 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/gauge.tsx',
    storybookId: 'components-gauge--docs',
  },
  {
    slug: 'heatmap-calendar',
    name: "HeatmapCalendar",
    nameZh: "热力日历",
    category: 'Business',
    desc: "HeatmapCalendar — a business component tailored to ERP/marketing scenarios.",
    descZh: "热力日历 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/heatmap-calendar.tsx',
    storybookId: 'components-heatmap-calendar--docs',
  },
  {
    slug: 'image-gallery',
    name: "ImageGallery",
    nameZh: "图片画廊",
    category: 'Business',
    desc: "ImageGallery — a business component tailored to ERP/marketing scenarios.",
    descZh: "ImageGallery — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/image-gallery.tsx',
    storybookId: 'components-image-gallery--docs',
  },
  {
    slug: 'inbox-list',
    name: "InboxList",
    nameZh: "收件列表",
    category: 'Business',
    desc: "InboxList — a business component tailored to ERP/marketing scenarios.",
    descZh: "InboxList — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/inbox-list.tsx',
    storybookId: 'components-inbox-list--docs',
  },
  {
    slug: 'invoice-preview',
    name: "InvoicePreview",
    nameZh: "发票预览",
    category: 'Business',
    desc: "InvoicePreview — a business component tailored to ERP/marketing scenarios.",
    descZh: "InvoicePreview — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/invoice-preview.tsx',
    storybookId: 'components-invoice-preview--docs',
  },
  {
    slug: 'json-viewer',
    name: "JsonViewer",
    nameZh: "JSON 查看器",
    category: 'Business',
    desc: "JsonViewer — a business component tailored to ERP/marketing scenarios.",
    descZh: "JSON 查看器 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/json-viewer.tsx',
    storybookId: 'components-json-viewer--docs',
  },
  {
    slug: 'kanban-board',
    name: "KanbanBoard",
    nameZh: "看板",
    category: 'Business',
    desc: "KanbanBoard — a business component tailored to ERP/marketing scenarios.",
    descZh: "看板 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/kanban-board.tsx',
    storybookId: 'components-kanban-board--docs',
  },
  {
    slug: 'kpi-card',
    name: "KpiCard",
    nameZh: "KPI 卡片",
    category: 'Business',
    desc: "KpiCard — a business component tailored to ERP/marketing scenarios.",
    descZh: "KPI 卡片 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/kpi-card.tsx',
    storybookId: 'components-kpi-card--docs',
  },
  {
    slug: 'language-switcher',
    name: "LanguageSwitcher",
    nameZh: "语言切换",
    category: 'Business',
    desc: "LanguageSwitcher — a business component tailored to ERP/marketing scenarios.",
    descZh: "语言切换 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/language-switcher.tsx',
    storybookId: 'components-language-switcher--docs',
  },
  {
    slug: 'loading-page',
    name: "LoadingPage",
    nameZh: "加载页",
    category: 'Business',
    desc: "LoadingPage — a business component tailored to ERP/marketing scenarios.",
    descZh: "加载页 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/loading-page.tsx',
    storybookId: 'components-loading-page--docs',
  },
  {
    slug: 'map-view',
    name: "MapView",
    nameZh: "地图视图",
    category: 'Business',
    desc: "MapView — a business component tailored to ERP/marketing scenarios.",
    descZh: "地图视图 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/map-view.tsx',
    storybookId: 'components-map-view--docs',
  },
  {
    slug: 'marketing',
    name: "Marketing",
    nameZh: "营销组件",
    category: 'Business',
    desc: "Marketing — a business component tailored to ERP/marketing scenarios.",
    descZh: "Marketing — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/marketing.tsx',
    storybookId: 'components-marketing--docs',
  },
  {
    slug: 'mask-input',
    name: "MaskInput",
    nameZh: "掩码输入",
    category: 'Business',
    desc: "MaskInput — a business component tailored to ERP/marketing scenarios.",
    descZh: "MaskInput — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mask-input.tsx',
    storybookId: 'components-mask-input--docs',
  },
  {
    slug: 'metric-trend',
    name: "MetricTrend",
    nameZh: "指标趋势",
    category: 'Business',
    desc: "MetricTrend — a business component tailored to ERP/marketing scenarios.",
    descZh: "指标趋势 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/metric-trend.tsx',
    storybookId: 'components-metric-trend--docs',
  },
  {
    slug: 'mobile-auth-layout',
    name: "MobileAuthLayout",
    nameZh: "移动鉴权布局",
    category: 'Business',
    desc: "MobileAuthLayout — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileAuthLayout — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-auth-layout.tsx',
    storybookId: 'components-mobile-auth-layout--docs',
  },
  {
    slug: 'mobile-bottom-nav',
    name: "MobileBottomNav",
    nameZh: "移动底部导航",
    category: 'Business',
    desc: "MobileBottomNav — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileBottomNav — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-bottom-nav.tsx',
    storybookId: 'components-mobile-bottom-nav--docs',
  },
  {
    slug: 'mobile-button',
    name: "MobileButton",
    nameZh: "移动按钮",
    category: 'Business',
    desc: "MobileButton — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileButton — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-button.tsx',
    storybookId: 'components-mobile-button--docs',
  },
  {
    slug: 'mobile-card',
    name: "MobileCard",
    nameZh: "移动卡片",
    category: 'Business',
    desc: "MobileCard — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileCard — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-card.tsx',
    storybookId: 'components-mobile-card--docs',
  },
  {
    slug: 'mobile-chart-fallback',
    name: "MobileChartFallback",
    nameZh: "移动图表回退",
    category: 'Business',
    desc: "MobileChartFallback — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileChartFallback — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-chart-fallback.tsx',
    storybookId: 'components-mobile-chart-fallback--docs',
  },
  {
    slug: 'mobile-dashboard-layout',
    name: "MobileDashboardLayout",
    nameZh: "移动工作台布局",
    category: 'Business',
    desc: "MobileDashboardLayout — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileDashboardLayout — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-dashboard-layout.tsx',
    storybookId: 'components-mobile-dashboard-layout--docs',
  },
  {
    slug: 'mobile-data-table',
    name: "MobileDataTable",
    nameZh: "移动数据表",
    category: 'Business',
    desc: "MobileDataTable — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileDataTable — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-data-table.tsx',
    storybookId: 'components-mobile-data-table--docs',
  },
  {
    slug: 'mobile-dialog',
    name: "MobileDialog",
    nameZh: "移动端对话框",
    category: 'Business',
    desc: "MobileDialog — a business component tailored to ERP/marketing scenarios.",
    descZh: "移动端对话框 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-dialog.tsx',
    storybookId: 'components-mobile-dialog--docs',
  },
  {
    slug: 'mobile-empty-state',
    name: "MobileEmptyState",
    nameZh: "移动空状态",
    category: 'Business',
    desc: "MobileEmptyState — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileEmptyState — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-empty-state.tsx',
    storybookId: 'components-mobile-empty-state--docs',
  },
  {
    slug: 'mobile-filter-builder',
    name: "MobileFilterBuilder",
    nameZh: "移动条件构建",
    category: 'Business',
    desc: "MobileFilterBuilder — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileFilterBuilder — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-filter-builder.tsx',
    storybookId: 'components-mobile-filter-builder--docs',
  },
  {
    slug: 'mobile-form',
    name: "MobileForm",
    nameZh: "移动表单",
    category: 'Business',
    desc: "MobileForm — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileForm — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-form.tsx',
    storybookId: 'components-mobile-form--docs',
  },
  {
    slug: 'mobile-form-autosave',
    name: "MobileFormAutosave",
    nameZh: "移动表单自动保存",
    category: 'Business',
    desc: "MobileFormAutosave — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileFormAutosave — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-form-autosave.tsx',
    storybookId: 'components-mobile-form-autosave--docs',
  },
  {
    slug: 'mobile-form-field',
    name: "MobileFormField",
    nameZh: "移动表单字段",
    category: 'Business',
    desc: "MobileFormField — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileFormField — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-form-field.tsx',
    storybookId: 'components-mobile-form-field--docs',
  },
  {
    slug: 'mobile-form-stepper',
    name: "MobileFormStepper",
    nameZh: "移动表单步骤",
    category: 'Business',
    desc: "MobileFormStepper — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileFormStepper — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-form-stepper.tsx',
    storybookId: 'components-mobile-form-stepper--docs',
  },
  {
    slug: 'mobile-form-wizard',
    name: "MobileFormWizard",
    nameZh: "移动表单向导",
    category: 'Business',
    desc: "MobileFormWizard — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileFormWizard — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-form-wizard.tsx',
    storybookId: 'components-mobile-form-wizard--docs',
  },
  {
    slug: 'mobile-input',
    name: "MobileInput",
    nameZh: "移动输入框",
    category: 'Business',
    desc: "MobileInput — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileInput — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-input.tsx',
    storybookId: 'components-mobile-input--docs',
  },
  {
    slug: 'mobile-kanban',
    name: "MobileKanban",
    nameZh: "移动看板",
    category: 'Business',
    desc: "MobileKanban — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileKanban — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-kanban.tsx',
    storybookId: 'components-mobile-kanban--docs',
  },
  {
    slug: 'mobile-kpi-card',
    name: "MobileKpiCard",
    nameZh: "移动KPI卡片",
    category: 'Business',
    desc: "MobileKpiCard — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileKpiCard — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-kpi-card.tsx',
    storybookId: 'components-mobile-kpi-card--docs',
  },
  {
    slug: 'mobile-navigation',
    name: "MobileNavigation",
    nameZh: "移动导航",
    category: 'Business',
    desc: "MobileNavigation — a business component tailored to ERP/marketing scenarios.",
    descZh: "移动导航 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-navigation.tsx',
    storybookId: 'components-mobile-navigation--docs',
  },
  {
    slug: 'mobile-page-header',
    name: "MobilePageHeader",
    nameZh: "移动页头",
    category: 'Business',
    desc: "MobilePageHeader — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobilePageHeader — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-page-header.tsx',
    storybookId: 'components-mobile-page-header--docs',
  },
  {
    slug: 'mobile-pull-to-refresh',
    name: "MobilePullToRefresh",
    nameZh: "移动下拉刷新",
    category: 'Business',
    desc: "MobilePullToRefresh — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobilePullToRefresh — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-pull-to-refresh.tsx',
    storybookId: 'components-mobile-pull-to-refresh--docs',
  },
  {
    slug: 'mobile-select',
    name: "MobileSelect",
    nameZh: "移动选择",
    category: 'Business',
    desc: "MobileSelect — a business component tailored to ERP/marketing scenarios.",
    descZh: "移动选择 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-select.tsx',
    storybookId: 'components-mobile-select--docs',
  },
  {
    slug: 'mobile-sheet',
    name: "MobileSheet",
    nameZh: "移动抽屉",
    category: 'Business',
    desc: "MobileSheet — a business component tailored to ERP/marketing scenarios.",
    descZh: "移动抽屉 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-sheet.tsx',
    storybookId: 'components-mobile-sheet--docs',
  },
  {
    slug: 'mobile-skeleton',
    name: "MobileSkeleton",
    nameZh: "移动骨架屏",
    category: 'Business',
    desc: "MobileSkeleton — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileSkeleton — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-skeleton.tsx',
    storybookId: 'components-mobile-skeleton--docs',
  },
  {
    slug: 'mobile-swipe-actions',
    name: "MobileSwipeActions",
    nameZh: "移动滑动操作",
    category: 'Business',
    desc: "MobileSwipeActions — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileSwipeActions — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-swipe-actions.tsx',
    storybookId: 'components-mobile-swipe-actions--docs',
  },
  {
    slug: 'mobile-tabs',
    name: "MobileTabs",
    nameZh: "移动标签页",
    category: 'Business',
    desc: "MobileTabs — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileTabs — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-tabs.tsx',
    storybookId: 'components-mobile-tabs--docs',
  },
  {
    slug: 'mobile-textarea',
    name: "MobileTextarea",
    nameZh: "移动文本域",
    category: 'Business',
    desc: "MobileTextarea — a business component tailored to ERP/marketing scenarios.",
    descZh: "MobileTextarea — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/mobile-textarea.tsx',
    storybookId: 'components-mobile-textarea--docs',
  },
  {
    slug: 'multi-select',
    name: "MultiSelect",
    nameZh: "多选",
    category: 'Business',
    desc: "MultiSelect — a business component tailored to ERP/marketing scenarios.",
    descZh: "MultiSelect — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/multi-select.tsx',
    storybookId: 'components-multi-select--docs',
  },
  {
    slug: 'notification-center',
    name: "NotificationCenter",
    nameZh: "通知中心",
    category: 'Business',
    desc: "NotificationCenter — a business component tailored to ERP/marketing scenarios.",
    descZh: "NotificationCenter — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/notification-center.tsx',
    storybookId: 'components-notification-center--docs',
  },
  {
    slug: 'onboarding-checklist',
    name: "OnboardingChecklist",
    nameZh: "新手清单",
    category: 'Business',
    desc: "OnboardingChecklist — a business component tailored to ERP/marketing scenarios.",
    descZh: "新手清单 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/onboarding-checklist.tsx',
    storybookId: 'components-onboarding-checklist--docs',
  },
  {
    slug: 'org-chart',
    name: "OrgChart",
    nameZh: "组织架构图",
    category: 'Business',
    desc: "OrgChart — a business component tailored to ERP/marketing scenarios.",
    descZh: "OrgChart — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/org-chart.tsx',
    storybookId: 'components-org-chart--docs',
  },
  {
    slug: 'page-header',
    name: "PageHeader",
    nameZh: "页头",
    category: 'Business',
    desc: "PageHeader — a business component tailored to ERP/marketing scenarios.",
    descZh: "页头 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/page-header.tsx',
    storybookId: 'components-page-header--docs',
  },
  {
    slug: 'payment-form',
    name: "PaymentForm",
    nameZh: "支付表单",
    category: 'Business',
    desc: "PaymentForm — a business component tailored to ERP/marketing scenarios.",
    descZh: "支付表单 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/payment-form.tsx',
    storybookId: 'components-payment-form--docs',
  },
  {
    slug: 'pdf-viewer',
    name: "PdfViewer",
    nameZh: "PDF查看器",
    category: 'Business',
    desc: "PdfViewer — a business component tailored to ERP/marketing scenarios.",
    descZh: "PdfViewer — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/pdf-viewer.tsx',
    storybookId: 'components-pdf-viewer--docs',
  },
  {
    slug: 'phone-input',
    name: "PhoneInput",
    nameZh: "电话输入",
    category: 'Business',
    desc: "PhoneInput — a business component tailored to ERP/marketing scenarios.",
    descZh: "PhoneInput — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/phone-input.tsx',
    storybookId: 'components-phone-input--docs',
  },
  {
    slug: 'pivot-table',
    name: "PivotTable",
    nameZh: "透视表",
    category: 'Business',
    desc: "PivotTable — a business component tailored to ERP/marketing scenarios.",
    descZh: "透视表 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/pivot-table.tsx',
    storybookId: 'components-pivot-table--docs',
  },
  {
    slug: 'presence-indicators',
    name: "PresenceIndicators",
    nameZh: "在线状态",
    category: 'Business',
    desc: "PresenceIndicators — a business component tailored to ERP/marketing scenarios.",
    descZh: "PresenceIndicators — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/presence-indicators.tsx',
    storybookId: 'components-presence-indicators--docs',
  },
  {
    slug: 'profile',
    name: "Profile",
    nameZh: "个人资料",
    category: 'Business',
    desc: "Profile — a business component tailored to ERP/marketing scenarios.",
    descZh: "Profile — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/profile.tsx',
    storybookId: 'components-profile--docs',
  },
  {
    slug: 'prompt-dialog',
    name: "PromptDialog",
    nameZh: "提示对话框",
    category: 'Business',
    desc: "PromptDialog — a business component tailored to ERP/marketing scenarios.",
    descZh: "提示对话框 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/prompt-dialog.tsx',
    storybookId: 'components-prompt-dialog--docs',
  },
  {
    slug: 'qr-code',
    name: "QrCode",
    nameZh: "二维码",
    category: 'Business',
    desc: "QrCode — a business component tailored to ERP/marketing scenarios.",
    descZh: "QrCode — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/qr-code.tsx',
    storybookId: 'components-qr-code--docs',
  },
  {
    slug: 'rating',
    name: "Rating",
    nameZh: "评分",
    category: 'Business',
    desc: "Rating — a business component tailored to ERP/marketing scenarios.",
    descZh: "评分 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/rating.tsx',
    storybookId: 'components-rating--docs',
  },
  {
    slug: 'responsive-preview',
    name: "ResponsivePreview",
    nameZh: "响应式预览",
    category: 'Business',
    desc: "ResponsivePreview — a business component tailored to ERP/marketing scenarios.",
    descZh: "响应式预览 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/responsive-preview.tsx',
    storybookId: 'components-responsive-preview--docs',
  },
  {
    slug: 'rich-text-editor',
    name: "RichTextEditor",
    nameZh: "富文本编辑器",
    category: 'Business',
    desc: "RichTextEditor — a business component tailored to ERP/marketing scenarios.",
    descZh: "RichTextEditor — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/rich-text-editor.tsx',
    storybookId: 'components-rich-text-editor--docs',
  },
  {
    slug: 'saved-filters',
    name: "SavedFilters",
    nameZh: "已存筛选",
    category: 'Business',
    desc: "SavedFilters — a business component tailored to ERP/marketing scenarios.",
    descZh: "已存筛选 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/saved-filters.tsx',
    storybookId: 'components-saved-filters--docs',
  },
  {
    slug: 'schedule-view',
    name: "ScheduleView",
    nameZh: "日程视图",
    category: 'Business',
    desc: "ScheduleView — a business component tailored to ERP/marketing scenarios.",
    descZh: "ScheduleView — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/schedule-view.tsx',
    storybookId: 'components-schedule-view--docs',
  },
  {
    slug: 'search-input',
    name: "SearchInput",
    nameZh: "搜索输入框",
    category: 'Business',
    desc: "SearchInput — a business component tailored to ERP/marketing scenarios.",
    descZh: "SearchInput — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/search-input.tsx',
    storybookId: 'components-search-input--docs',
  },
  {
    slug: 'segmented-control',
    name: "SegmentedControl",
    nameZh: "分段控件",
    category: 'Business',
    desc: "SegmentedControl — a business component tailored to ERP/marketing scenarios.",
    descZh: "分段控件 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/segmented-control.tsx',
    storybookId: 'components-segmented-control--docs',
  },
  {
    slug: 'settings-layout',
    name: "SettingsLayout",
    nameZh: "设置布局",
    category: 'Business',
    desc: "SettingsLayout — a business component tailored to ERP/marketing scenarios.",
    descZh: "SettingsLayout — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/settings-layout.tsx',
    storybookId: 'components-settings-layout--docs',
  },
  {
    slug: 'signature-pad',
    name: "SignaturePad",
    nameZh: "签名板",
    category: 'Business',
    desc: "SignaturePad — a business component tailored to ERP/marketing scenarios.",
    descZh: "签名板 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/signature-pad.tsx',
    storybookId: 'components-signature-pad--docs',
  },
  {
    slug: 'stat-card',
    name: "StatCard",
    nameZh: "统计卡",
    category: 'Business',
    desc: "StatCard — a business component tailored to ERP/marketing scenarios.",
    descZh: "统计卡 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/stat-card.tsx',
    storybookId: 'components-stat-card--docs',
  },
  {
    slug: 'status-tag',
    name: "StatusTag",
    nameZh: "状态标签",
    category: 'Business',
    desc: "StatusTag — a business component tailored to ERP/marketing scenarios.",
    descZh: "状态标签 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/status-tag.tsx',
    storybookId: 'components-status-tag--docs',
  },
  {
    slug: 'theme-toggle',
    name: "ThemeToggle",
    nameZh: "主题切换",
    category: 'Business',
    desc: "ThemeToggle — a business component tailored to ERP/marketing scenarios.",
    descZh: "主题切换 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/theme-toggle.tsx',
    storybookId: 'components-theme-toggle--docs',
  },
  {
    slug: 'time-picker',
    name: "TimePicker",
    nameZh: "时间选择",
    category: 'Business',
    desc: "TimePicker — a business component tailored to ERP/marketing scenarios.",
    descZh: "时间选择 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/time-picker.tsx',
    storybookId: 'components-time-picker--docs',
  },
  {
    slug: 'top-loader',
    name: "TopLoader",
    nameZh: "顶部加载条",
    category: 'Business',
    desc: "TopLoader — a business component tailored to ERP/marketing scenarios.",
    descZh: "TopLoader — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/top-loader.tsx',
    storybookId: 'components-top-loader--docs',
  },
  {
    slug: 'tour',
    name: "Tour",
    nameZh: "导览",
    category: 'Business',
    desc: "Tour — a business component tailored to ERP/marketing scenarios.",
    descZh: "导览 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/tour.tsx',
    storybookId: 'components-tour--docs',
  },
  {
    slug: 'transfer',
    name: "Transfer",
    nameZh: "穿梭框",
    category: 'Business',
    desc: "Transfer — a business component tailored to ERP/marketing scenarios.",
    descZh: "穿梭框 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/transfer.tsx',
    storybookId: 'components-transfer--docs',
  },
  {
    slug: 'user-menu',
    name: "UserMenu",
    nameZh: "用户菜单",
    category: 'Business',
    desc: "UserMenu — a business component tailored to ERP/marketing scenarios.",
    descZh: "用户菜单 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/user-menu.tsx',
    storybookId: 'components-user-menu--docs',
  },
  {
    slug: 'video-player',
    name: "VideoPlayer",
    nameZh: "视频播放器",
    category: 'Business',
    desc: "VideoPlayer — a business component tailored to ERP/marketing scenarios.",
    descZh: "VideoPlayer — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/video-player.tsx',
    storybookId: 'components-video-player--docs',
  },
  {
    slug: 'watermark',
    name: "Watermark",
    nameZh: "水印",
    category: 'Business',
    desc: "Watermark — a business component tailored to ERP/marketing scenarios.",
    descZh: "水印 — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/watermark.tsx',
    storybookId: 'components-watermark--docs',
  },
  {
    slug: 'workflow',
    name: "Workflow",
    nameZh: "工作流",
    category: 'Business',
    desc: "Workflow — a business component tailored to ERP/marketing scenarios.",
    descZh: "Workflow — 业务组件,贴合 ERP/营销等垂直场景。",
    sourcePath: 'packages/chaos-design-ui/components/business/workflow.tsx',
    storybookId: 'components-workflow--docs',
  },
  {
    slug: 'app-shell',
    name: "AppShell",
    nameZh: "应用外壳",
    category: 'System Layout',
    desc: "AppShell — a system-level layout shell for admin and dashboard pages.",
    descZh: "应用外壳 — 体系级布局外壳,适用于后台与工作台页面。",
    sourcePath: 'packages/chaos-design-ui/components/layout/app-shell.tsx',
    storybookId: 'components-app-shell--docs',
  },
  {
    slug: 'auth-layout',
    name: "AuthLayout",
    nameZh: "鉴权布局",
    category: 'System Layout',
    desc: "AuthLayout — a system-level layout shell for admin and dashboard pages.",
    descZh: "鉴权布局 — 体系级布局外壳,适用于后台与工作台页面。",
    sourcePath: 'packages/chaos-design-ui/components/layout/auth-layout.tsx',
    storybookId: 'components-auth-layout--docs',
  },
  {
    slug: 'blank-layout',
    name: "BlankLayout",
    nameZh: "空白布局",
    category: 'System Layout',
    desc: "BlankLayout — a system-level layout shell for admin and dashboard pages.",
    descZh: "空白布局 — 体系级布局外壳,适用于后台与工作台页面。",
    sourcePath: 'packages/chaos-design-ui/components/layout/blank-layout.tsx',
    storybookId: 'components-blank-layout--docs',
  },
  {
    slug: 'dashboard-layout',
    name: "DashboardLayout",
    nameZh: "工作台布局",
    category: 'System Layout',
    desc: "DashboardLayout — a system-level layout shell for admin and dashboard pages.",
    descZh: "工作台布局 — 体系级布局外壳,适用于后台与工作台页面。",
    sourcePath: 'packages/chaos-design-ui/components/layout/dashboard-layout.tsx',
    storybookId: 'components-dashboard-layout--docs',
  },
  {
    slug: 'detail-layout',
    name: "DetailLayout",
    nameZh: "详情布局",
    category: 'System Layout',
    desc: "DetailLayout — a system-level layout shell for admin and dashboard pages.",
    descZh: "详情布局 — 体系级布局外壳,适用于后台与工作台页面。",
    sourcePath: 'packages/chaos-design-ui/components/layout/detail-layout.tsx',
    storybookId: 'components-detail-layout--docs',
  },
  {
    slug: 'error-layout',
    name: "ErrorLayout",
    nameZh: "错误布局",
    category: 'System Layout',
    desc: "ErrorLayout — a system-level layout shell for admin and dashboard pages.",
    descZh: "错误布局 — 体系级布局外壳,适用于后台与工作台页面。",
    sourcePath: 'packages/chaos-design-ui/components/layout/error-layout.tsx',
    storybookId: 'components-error-layout--docs',
  },
  {
    slug: 'print-layout',
    name: "PrintLayout",
    nameZh: "打印布局",
    category: 'System Layout',
    desc: "PrintLayout — a system-level layout shell for admin and dashboard pages.",
    descZh: "打印布局 — 体系级布局外壳,适用于后台与工作台页面。",
    sourcePath: 'packages/chaos-design-ui/components/layout/print-layout.tsx',
    storybookId: 'components-print-layout--docs',
  },
  {
    slug: 'public-layout',
    name: "PublicLayout",
    nameZh: "公共布局",
    category: 'System Layout',
    desc: "PublicLayout — a system-level layout shell for admin and dashboard pages.",
    descZh: "公共布局 — 体系级布局外壳,适用于后台与工作台页面。",
    sourcePath: 'packages/chaos-design-ui/components/layout/public-layout.tsx',
    storybookId: 'components-public-layout--docs',
  },
  {
    slug: 'top-bar',
    name: "TopBar",
    nameZh: "顶部栏",
    category: 'System Layout',
    desc: "TopBar — a system-level layout shell for admin and dashboard pages.",
    descZh: "顶部栏 — 体系级布局外壳,适用于后台与工作台页面。",
    sourcePath: 'packages/chaos-design-ui/components/layout/top-bar.tsx',
    storybookId: 'components-top-bar--docs',
  },
]
