import type { BusinessSubCategory } from "@/lib/business-subcategories";

/**
 * Explicit Business slug → sub-group overrides.
 * Applied before heuristic regex so high-traffic / glue components land correctly.
 */
export const BUSINESS_SUBCATEGORY_OVERRIDES: Record<string, BusinessSubCategory> =
  {
    // list / tables
    "advanced-data-table": "list",
    "ar-ap-aging-table": "list",
    "attachment-list": "list",
    "bill-todo-list": "list",
    "data-table": "list",
    "diff-viewer-table": "list",
    "editable-tree-table": "list",
    "import-error-table": "list",
    "inventory-alert-list": "list",
    "list-page-shell": "list",
    "master-list-template": "list",
    "message-list": "list",
    "performance-rank-table": "list",
    "pivot-table": "list",
    "pool-tracker-table": "list",
    "search-table": "list",
    "tab-crud-page": "list",
    "task-list-table": "list",
    "tax-detail-table": "list",
    "todo-list-table": "list",
    "tree-crud-page": "list",
    "tree-table": "list",
    "crud-page": "list",
    "bar-list": "list",
    "bar-list-card": "list",
    "mobile-list-item": "list",
    "batch-genealogy-tree": "list",
    "bom-tree-editor": "list",
    "kanban-board": "list",
    "kanban-column": "list",

    // report / charts
    chart: "report",
    "chart-card": "report",
    "chart-suite": "report",
    "area-chart": "report",
    "bar-chart": "report",
    "donut-chart": "report",
    "funnel-chart": "report",
    "gantt-chart": "report",
    "gantt-chart-pro": "report",
    "gauge-chart": "report",
    "heatmap-chart": "report",
    "line-chart": "report",
    "map-chart": "report",
    "metric-trend": "report",
    "org-chart": "report",
    "pie-chart": "report",
    "radar-chart": "report",
    "radial-chart": "report",
    "sankey-chart": "report",
    "scatter-chart": "report",
    "spark-chart": "report",
    "spc-control-chart": "report",
    "treemap-chart": "report",
    "waterfall-chart": "report",
    "invoice-summary": "report",

    // dashboard
    "kpi-card": "dashboard",
    "overview-page": "dashboard",
    "activity-feed": "dashboard",
    "async-task-center": "dashboard",
    "async-task-trigger": "dashboard",
    "global-loading": "dashboard",
    "loading-page": "dashboard",
    "feature-tour": "dashboard",

    // approval / workflow
    "approval-action-bar": "approval",
    "workflow-designer": "approval",
    "workflow-preview": "approval",
    "sign-action-button": "approval",
    "status-action-buttons": "approval",
    "auth-guard": "approval",
    "compliance-checklist": "approval",

    // detail / cards / bills
    "bill-page": "detail",
    "bill-header": "detail",
    "bill-footer": "detail",
    "bill-status-bar": "detail",
    "bill-timeline": "detail",
    "bill-print-template": "detail",
    "biz-status-tag": "detail",
    "campaign-card": "detail",
    "campaign-status-tag": "detail",
    "customer-360-card": "detail",
    "error-page": "detail",
    "invoice-manager": "detail",
    "page-header": "detail",
    "record-count": "detail",
    "settlement-status-tag": "detail",
    "status-badge": "detail",
    "status-tag": "detail",
    "work-order-card": "detail",
    "chat-shell": "detail",
    "chat-header": "detail",
    "chat-feedback": "detail",
    "chat-agent-status": "detail",
    "mobile-page-shell": "detail",

    // modal / dialog
    "batch-print-dialog": "modal",
    "browse-dialog": "modal",
    "confirm-dialog": "modal",
    "dict-manage-dialog": "modal",
    "form-dialog": "modal",
    "import-dialog": "modal",
    "prompt-dialog": "modal",
    "stock-transfer-dialog": "modal",
    "mobile-action-sheet": "modal",

    // toolbar / actions
    "bulk-actions-toolbar": "toolbar",
    "crud-toolbar": "toolbar",
    "edit-toolbar": "toolbar",
    "chat-input-toolbar": "toolbar",
    "chat-message-actions": "toolbar",
    "filter-bar": "toolbar",
    "filter-builder": "toolbar",
    "saved-filters": "toolbar",
    "advanced-search": "toolbar",
    "chat-conversation-search": "toolbar",
    "refresh-button": "toolbar",
    "subform-tabs": "toolbar",

    // picker / browse / form inputs
    "address-picker": "picker",
    "application-form": "picker",
    "attachment-uploader": "picker",
    "batch-selector": "picker",
    "channel-picker": "picker",
    "chat-mention-picker": "picker",
    "city-browse": "picker",
    "company-browse": "picker",
    "company-picker": "picker",
    "cost-center-picker": "picker",
    "customer-browse": "picker",
    "customer-picker": "picker",
    "date-range-picker": "picker",
    "department-picker": "picker",
    "dict-select": "picker",
    "distributor-picker": "picker",
    "dynamic-form-builder": "picker",
    "employee-picker": "picker",
    "fee-type-browse": "picker",
    "file-upload-manager": "picker",
    "form-designer": "picker",
    "form-designer-runtime": "picker",
    "form-field": "picker",
    "form-wizard": "picker",
    "formula-editor": "picker",
    "gift-line-editor": "picker",
    "i18n-form-field": "picker",
    "invoice-title-picker": "picker",
    "leave-request-form": "picker",
    "marketing-activity-form": "picker",
    "mobile-picker": "picker",
    "multi-select": "picker",
    "order-line-editor": "picker",
    "org-picker": "picker",
    "paste-upload": "picker",
    "payment-method-selector": "picker",
    "price-adjust-browse": "picker",
    "price-ladder-editor": "picker",
    "price-match-result": "picker",
    "product-browse": "picker",
    "product-category-picker": "picker",
    "purchase-order-editor": "picker",
    "quality-inspection-form": "picker",
    "rebut-node-select": "picker",
    "region-picker": "picker",
    "remote-select": "picker",
    "sales-order-browse": "picker",
    "sales-target-editor": "picker",
    "shipping-way-browse": "picker",
    "sku-picker": "picker",
    "user-picker": "picker",
    "warehouse-browse": "picker",
    "warehouse-picker": "picker",
    "writeoff-browse": "picker",
    "writeoff-flow": "picker",
    "audio-recorder": "picker",
    "media-recorder": "picker",

    // calendar / schedule → detail-ish dashboard
    "attendance-calendar": "dashboard",
    "calendar-view": "dashboard",
    "campaign-calendar": "dashboard",
    "heatmap-calendar": "dashboard",
    "shift-calendar": "dashboard",

    // chat suite
    "chat-artifact-panel": "detail",
    "chat-branch": "detail",
    "chat-code-block": "detail",
    "chat-command-menu": "toolbar",
    "chat-context-panel": "detail",
    "chat-conversation": "detail",
    "chat-image-gallery": "detail",
    "chat-markdown-renderer": "detail",
    "chat-message-bubble": "detail",
    "chat-message-group": "detail",
    "chat-message-input": "picker",
    "chat-model-switcher": "toolbar",
    "chat-sidebar": "detail",
    "chat-streaming-text": "detail",
    "chat-suggest-replies": "toolbar",
    "chat-thinking-block": "detail",
    "chat-tool-call-block": "detail",
    "chat-voice-message": "detail",
    "announcement-banner": "detail",
    "avatar-group": "detail",
    "badge-delta": "detail",
    "callout": "detail",
    "category-bar": "report",
    "checkout-bar": "toolbar",
    "chip": "detail",
    "bulk-import-wizard": "picker",
    "audience-segment-builder": "picker",
    "barcode-scanner": "picker",
    "budget-allocator": "detail",
  };
